/**
 * LAVI FINANCE PRO — TELEGRAM BOT FOR GAS BACKEND
 * Ported from lavi-finance.py (Python polling bot) to Google Apps Script webhook.
 *
 * Script Properties:
 *   LAVI_FINANCE_TELEGRAM_TOKEN
 *   LAVI_FINANCE_TELEGRAM_ALLOWED_CHAT_IDS   comma/semicolon/newline separated
 *   LAVI_FINANCE_TELEGRAM_WEBHOOK_KEY        auto-generated by setup if absent
 *
 * Public setup helpers:
 *   setupLaviFinanceTelegram()
 *   checkLaviFinanceTelegramStatus()
 *   resetLaviFinanceTelegramSession(chatId)
 *
 * Webhook is routed by Kode.js doPost() into handleLaviTelegramWebhook_().
 */

const LAVI_FINANCE_TELEGRAM = (() => {
  'use strict';

  const VERSION = '3.4.0-gas-relay';
  const TZ = 'Asia/Jakarta';
  const PROP = Object.freeze({
    TOKEN: 'LAVI_FINANCE_TELEGRAM_TOKEN',
    ALLOWED: 'LAVI_FINANCE_TELEGRAM_ALLOWED_CHAT_IDS',
    WEBHOOK_KEY: 'LAVI_FINANCE_TELEGRAM_WEBHOOK_KEY',
    PERSON_PREFIX: 'LAVI_FINANCE_TELEGRAM_PERSON_',
    SESSION_PREFIX: 'LAVI_FINANCE_TELEGRAM_SESSION_'
  });
  const CACHE_TTL = 60;
  const TX_FETCH_LIMIT = 200;
  const ITEMS_PER_PAGE = 20;
  const TX_PER_PAGE = 10;
  const SESSION_TTL_MS = 24 * 60 * 60 * 1000;

  const DEFAULT_PERSONS = ['Abi','Ummah','Dafiq','Laviska','Toko'];
  const FALLBACK_CATEGORIES = Object.freeze({
    pemasukan: [
      'Bagi Hasil','Bunga Tabungan','Capital Gain','Cashback','Dividen','Freelance / Proyek','Gaji / Upah','Hadiah','Hibah','Honor Tetap',
      'Jasa','Jual Aset Pribadi','Komisi / Affiliate','Laba Usaha','Penjualan Produk','Penyesuaian','Piutang Masuk','Pinjaman & Hutang','Refund','Reimburse','Royalti',
      'Saldo Top-Up','Sewa Properti','Tabungan / Investasi','THR / Bonus','Titipan','Tunjangan','Uang Bulanan','Uang Tambahan','Undian','Usaha Sampingan','Warisan'
    ],
    pengeluaran: [
      'Air Minum & Gas','BBM','Belanja Bulanan','Belanja Harian','Belanja Mingguan','Buku & Kursus','Dana Darurat','Dokter / Klinik','Hadiah & Kado','Hobi & Pribadi',
      'Hutang & Cicilan','Internet & TV Kabel','Iuran Kas','Jasa Lainnya','Kebersihan','Kebutuhan Anak','Keluarga & Orang Tua','Langganan Aplikasi','Listrik & Air',
      'Makanan & Minuman','Nongkrong / Hiburan','Obat-obatan','Ojek Online','Ongkos Kirim','Pajak & Admin Bank','Pakaian & Aksesoris','Parkir & Tol',
      'Pemberian Pinjaman','Penyesuaian','Piutang Keluar','Pulsa & Data','Rumah Tangga','SPP / Pendidikan','Sembako','Servis Kendaraan','Sewa / Cicilan Rumah',
      'Skincare & Grooming','Sumbangan & Donasi','Tabungan / Investasi','Transport Umum','Traveling','Zakat / Sedekah'
    ],
    jenisSaldo: ['Cash','Rekening','SeaBank','Shopeepay','Bank Jago','Dana','Gopay','E-Money','Kartu Kredit','Penyesuaian'],
    jenisTabungan: ['Bibit (Reksadana)','Emas (Investasi)','Stockbit (Saham)','Celengan']
  });
  const HARI = ['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'];
  const BULAN = ['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];

  function props_() { return PropertiesService.getScriptProperties(); }
  function token_() { return String(props_().getProperty(PROP.TOKEN) || '').trim(); }
  function allowedIds_() {
    const raw = String(props_().getProperty(PROP.ALLOWED) || '').trim();
    if (!raw) return [];
    try {
      const arr = JSON.parse(raw);
      if (Array.isArray(arr)) return Array.from(new Set(arr.map(String).map(v => v.trim()).filter(Boolean)));
    } catch (_) {}
    return Array.from(new Set(raw.split(/[\s,;]+/).map(v => v.trim()).filter(Boolean)));
  }
  function isAllowed_(chatId) {
    const ids = allowedIds_();
    return ids.length > 0 && ids.indexOf(String(chatId)) !== -1;
  }
  function webhookKey_() { return String(props_().getProperty(PROP.WEBHOOK_KEY) || '').trim(); }
  function getOrCreateWebhookKey_() {
    let key = webhookKey_();
    if (!key) {
      key = Utilities.getUuid().replace(/-/g,'') + Utilities.getUuid().replace(/-/g,'');
      props_().setProperty(PROP.WEBHOOK_KEY, key);
    }
    return key;
  }
  function sessionKey_(chatId) { return PROP.SESSION_PREFIX + String(chatId); }
  function personKey_(chatId) { return PROP.PERSON_PREFIX + String(chatId); }
  function sessionCacheKey_(chatId) { return 'lftg_sess_' + String(chatId); }
  function getSession_(chatId) {
    const cache = CacheService.getScriptCache();
    let raw = null;
    try { raw = cache.get(sessionCacheKey_(chatId)); } catch (_) {}
    if (!raw) raw = props_().getProperty(sessionKey_(chatId));
    if (!raw) return { step:'MENU', _updatedAt:Date.now() };
    try {
      const s = JSON.parse(raw) || {};
      if (s._updatedAt && Date.now() - Number(s._updatedAt) > SESSION_TTL_MS) return { step:'MENU', _updatedAt:Date.now() };
      try { cache.put(sessionCacheKey_(chatId), JSON.stringify(s), 21600); } catch (_) {}
      return s;
    } catch (_) { return { step:'MENU', _updatedAt:Date.now() }; }
  }
  function saveSession_(chatId, session) {
    session = session || {};
    session._updatedAt = Date.now();
    let json = JSON.stringify(session);
    if (json.length > 8500) {
      const compact = {
        step: session.step || 'MENU', last_msg_id: session.last_msg_id || null, last_payload: session.last_payload || null,
        last_transaction_id: session.last_transaction_id || null, last_transaction_at: session.last_transaction_at || null,
        filter_state: session.filter_state || null, export_spec: session.export_spec || null, tanggal:session.tanggal, person:session.person, jenis:session.jenis,
        kategori:session.kategori, saldo:session.saldo, saldo_asal:session.saldo_asal, saldo_tujuan:session.saldo_tujuan,
        person_tujuan:session.person_tujuan, nominal:session.nominal, keterangan:session.keterangan,
        editing_tx:session.editing_tx || null, deleting_tx:session.deleting_tx || null, keypad_val:session.keypad_val || '', _updatedAt:Date.now()
      };
      json = JSON.stringify(compact);
    }
    try { CacheService.getScriptCache().put(sessionCacheKey_(chatId), json, 21600); } catch (_) {}
    // Persist compact session so a cache eviction never breaks an in-progress wizard.
    props_().setProperty(sessionKey_(chatId), json);
  }
  function resetSession_(chatId, preserveMsg) {
    const old = getSession_(chatId);
    const next = { step:'MENU', _updatedAt:Date.now() };
    if (preserveMsg && old.last_msg_id) next.last_msg_id = old.last_msg_id;
    if (old.last_payload) next.last_payload = old.last_payload;
    if (old.last_transaction_id) next.last_transaction_id = old.last_transaction_id;
    if (old.last_transaction_at) next.last_transaction_at = old.last_transaction_at;
    saveSession_(chatId, next);
    return next;
  }
  function getMappedPerson_(chatId) { return String(props_().getProperty(personKey_(chatId)) || '').trim(); }
  function setMappedPerson_(chatId, person) {
    if (person) props_().setProperty(personKey_(chatId), String(person));
    else props_().deleteProperty(personKey_(chatId));
  }

  function tg_(method, payload, retries) {
    const token = token_();
    if (!token) throw new Error('LAVI_FINANCE_TELEGRAM_TOKEN belum dikonfigurasi.');
    let lastErr = null;
    const max = Math.max(0, Number(retries == null ? 1 : retries));
    for (let attempt=0; attempt<=max; attempt++) {
      try {
        const res = UrlFetchApp.fetch('https://api.telegram.org/bot' + token + '/' + method, {
          method:'post', contentType:'application/json', payload:JSON.stringify(payload || {}), muteHttpExceptions:true
        });
        const code = res.getResponseCode();
        let body = {};
        try { body = JSON.parse(res.getContentText()); } catch (_) {}
        if (code >= 200 && code < 300 && body.ok) return body.result;
        lastErr = new Error('Telegram ' + method + ' HTTP ' + code + ': ' + String(body.description || res.getContentText()).slice(0,300));
      } catch (e) { lastErr = e; }
      if (attempt < max) Utilities.sleep(500);
    }
    throw lastErr || new Error('Telegram API gagal.');
  }
  function tgDocument_(chatId, blob, caption) {
    const token=token_();if(!token)throw new Error('Token Telegram belum dikonfigurasi.');
    const res=UrlFetchApp.fetch('https://api.telegram.org/bot'+token+'/sendDocument',{
      method:'post',payload:{chat_id:String(chatId),document:blob,caption:String(caption||'').slice(0,900)},muteHttpExceptions:true
    });
    let body={};try{body=JSON.parse(res.getContentText());}catch(_){}
    if(res.getResponseCode()<200||res.getResponseCode()>=300||!body.ok)throw new Error('Telegram sendDocument gagal: '+String(body.description||res.getContentText()).slice(0,240));
    return body.result;
  }
  function answerCb_(id, text, alert) {
    try { tg_('answerCallbackQuery',{ callback_query_id:id, text:text || '', show_alert:!!alert },0); } catch (_) {}
  }
  function deleteMessage_(chatId, messageId) {
    if (!messageId) return;
    try { tg_('deleteMessage',{chat_id:String(chatId),message_id:Number(messageId)},0); } catch (_) {}
  }
  function keyboard_(rows) { return { inline_keyboard: rows || [] }; }
  function btn_(text, data) { return { text:String(text), callback_data:String(data) }; }
  function urlBtn_(text, url) { return { text:String(text), url:String(url) }; }
  function sendOrEdit_(chatId, text, rows, options) {
    options = options || {};
    const s = getSession_(chatId);
    const markup = rows ? keyboard_(rows) : undefined;
    const payload = { chat_id:String(chatId), text:String(text), parse_mode:'HTML', disable_web_page_preview:true };
    if (markup) payload.reply_markup = markup;
    let msg = null;
    if (s.last_msg_id && options.forceNew !== true) {
      try {
        const ep = Object.assign({}, payload, {message_id:Number(s.last_msg_id)});
        msg = tg_('editMessageText',ep,0);
      } catch (err) {
        // Same menu/text is already visible: treat as success, never create a duplicate message.
        if (String(err && err.message || err).toLowerCase().indexOf('message is not modified') >= 0) return {message_id:Number(s.last_msg_id), unchanged:true};
      }
    }
    if (!msg) msg = tg_('sendMessage',payload,0);
    if (msg && msg.message_id) { s.last_msg_id = msg.message_id; saveSession_(chatId,s); }
    return msg;
  }
  // Animations are intentionally disabled in webhook mode. Multiple Telegram API calls + sleep
  // delay the HTTP acknowledgement and can make Telegram redeliver the same update.
  function progress_(chatId, title, steps) { return null; }

  function esc_(v) { return String(v == null ? '' : v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
  function rupiah_(n) {
    const v = Math.round(Number(n) || 0);
    const sign = v < 0 ? '-' : '';
    return sign + 'Rp ' + String(Math.abs(v)).replace(/\B(?=(\d{3})+(?!\d))/g,'.');
  }
  function now_() { return new Date(); }
  function fmtDate_(d) { return Utilities.formatDate(d || new Date(),TZ,'dd/MM/yyyy'); }
  function fmtTime_(d) { return Utilities.formatDate(d || new Date(),TZ,'HH:mm'); }
  function parseDate_(s) {
    const m = String(s || '').trim().match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
    if (!m) return null;
    const d = new Date(Number(m[3]),Number(m[2])-1,Number(m[1]),12,0,0);
    return (d.getFullYear()===Number(m[3]) && d.getMonth()===Number(m[2])-1 && d.getDate()===Number(m[1])) ? d : null;
  }
  function menuText_() {
    const d = now_();
    return '<b>💎 LAVI FINANCE PRO</b>\n━━━━━━━━━━━━━━━━━━━━\n📅 '+HARI[d.getDay()]+', '+Number(Utilities.formatDate(d,TZ,'d'))+' '+BULAN[Number(Utilities.formatDate(d,TZ,'M'))-1]+' '+Utilities.formatDate(d,TZ,'yyyy')+'\n🕐 '+fmtTime_(d)+' WIB\n\nPilih menu pencatatan & kelola keuangan:';
  }
  function mainMenu_() { return [
    [btn_('➕ Transaksi Baru','wizard_start'),btn_('💰 Cek Saldo','btn_cek_saldo')],
    [btn_('📊 Dashboard Bulan Ini','btn_dashboard_month'),btn_('📅 Transaksi Hari Ini','btn_today_summary')],
    [btn_('📜 10 Transaksi Terakhir','btn_recent_10'),btn_('🔍 Filter & Cari','btn_filter_menu')],
    [btn_('📈 Statistik Ringkas','btn_stats'),btn_('📄 Export Excel / PDF','btn_export')],
    [btn_('🩺 Status Sistem','btn_system_status'),urlBtn_('🌐 Buka Aplikasi','https://finance.lavi.web.id')],
    [btn_('❓ Bantuan & Info','btn_help')]
  ]; }
  function personMenu_() {
    const rows=[]; let row=[];
    DEFAULT_PERSONS.forEach(p=>{ row.push(btn_('👤 '+p,'set_person:'+p)); if(row.length===2){rows.push(row);row=[];} });
    if(row.length) rows.push(row);
    rows.push([btn_('✏️ Nama Custom','prompt_custom_person')]); rows.push([btn_('◀️ Batal / Menu Utama','btn_menu')]); return rows;
  }
  function typeMenu_(hasMapped) {
    const rows=[[btn_('🔴 Pengeluaran','set_type:Pengeluaran'),btn_('🟢 Pemasukan','set_type:Pemasukan')],[btn_('🔄 Pemindahan Saldo','set_type:Pemindahan Saldo'),btn_('📈 Investasi & Tabungan','set_type:Investasi dan Tabungan')]];
    if(hasMapped) rows.push([btn_('👤 Ganti Person Transaksi Ini','wizard_start_manual')]);
    rows.push([btn_('◀️ Kembali','wizard_start'),btn_('❌ Batal','btn_menu')]); return rows;
  }
  function masterData_() {
    const cache = CacheService.getScriptCache(), key = 'lftg_master_v1';
    try { const raw = cache.get(key); if (raw) return JSON.parse(raw); } catch (_) {}
    try {
      const c = fetchCategories();
      if (c && c.pemasukan && c.pengeluaran) {
        try { cache.put(key, JSON.stringify(c), 21600); } catch (_) {}
        return c;
      }
    } catch (_) {}
    return JSON.parse(JSON.stringify(FALLBACK_CATEGORIES));
  }
  function categoriesFor_(jenis) {
    if (jenis === 'Pemindahan Saldo') return ['Pemindahan Saldo'];
    const m = masterData_();
    if (jenis === 'Pemasukan') return m.pemasukan || FALLBACK_CATEGORIES.pemasukan;
    if (jenis === 'Investasi dan Tabungan') return m.jenisTabungan || FALLBACK_CATEGORIES.jenisTabungan;
    return m.pengeluaran || FALLBACK_CATEGORIES.pengeluaran;
  }
  function wallets_() { const m=masterData_(); return (m.jenisSaldo && m.jenisSaldo.length ? m.jenisSaldo : FALLBACK_CATEGORIES.jenisSaldo).slice(); }
  function categoryMenu_(jenis,page,edit) {
    const all=categoriesFor_(jenis), pages=Math.max(1,Math.ceil(all.length/ITEMS_PER_PAGE)); page=Math.max(1,Math.min(Number(page)||1,pages));
    const list=all.slice((page-1)*ITEMS_PER_PAGE,page*ITEMS_PER_PAGE), rows=[]; let row=[];
    list.forEach(c=>{ row.push(btn_(c,(edit?'save_edit_field:kategoriPilihan:':'set_cat:')+c)); if(row.length===2){rows.push(row);row=[];} }); if(row.length)rows.push(row);
    if(pages>1) rows.push([btn_('⬅️ Prev',(edit?'edit_cat_page:':'cat_page:')+(page>1?page-1:pages)),btn_('📄 '+page+'/'+pages,'noop'),btn_('Next ➡️',(edit?'edit_cat_page:':'cat_page:')+(page<pages?page+1:1))]);
    rows.push([btn_('✏️ Ketik '+(edit?'Custom':'Kategori Custom'),edit?'prompt_edit_custom_cat':'prompt_custom_cat')]);
    rows.push([btn_('◀️ '+(edit?'Batal Edit':'Kembali'),edit?'edit_back_to_summary':'set_type_back'),btn_('❌ Batal','btn_menu')]); return rows;
  }
  function walletMenu_(transferKind) {
    const rows=[]; let row=[];
    wallets_().forEach(s=>{ if(transferKind && s==='Penyesuaian')return; const prefix=transferKind==='asal'?'set_saldo_asal:':transferKind==='tujuan'?'set_saldo_tujuan:':'set_saldo:'; row.push(btn_((s==='Cash'?'💵 ':s.indexOf('Kartu')>=0?'💳 ':'🏦 ')+s,prefix+s)); if(row.length===2){rows.push(row);row=[];} }); if(row.length)rows.push(row);
    if(transferKind) rows.push([btn_('◀️ Kembali',transferKind==='asal'?'set_type_back':'set_saldo_asal_back'),btn_('❌ Batal','btn_menu')]);
    else rows.push([btn_('◀️ Kembali','set_cat_back'),btn_('❌ Batal','btn_menu')]); return rows;
  }
  function targetPersonMenu_(origin) {
    const rows=[[btn_('👤 Person Sama ('+origin+')','set_person_tujuan:'+origin)]], other=DEFAULT_PERSONS.filter(p=>p!==origin); let row=[];
    other.forEach(p=>{row.push(btn_('👤 '+p,'set_person_tujuan:'+p));if(row.length===2){rows.push(row);row=[];}});if(row.length)rows.push(row);
    rows.push([btn_('◀️ Kembali','set_saldo_tujuan_back'),btn_('❌ Batal','btn_menu')]); return rows;
  }
  function nominalMenu_() { return [
    [btn_('5.000','set_nom:5000'),btn_('10.000','set_nom:10000'),btn_('15.000','set_nom:15000')],
    [btn_('20.000','set_nom:20000'),btn_('25.000','set_nom:25000'),btn_('50.000','set_nom:50000')],
    [btn_('75.000','set_nom:75000'),btn_('100.000','set_nom:100000'),btn_('150.000','set_nom:150000')],
    [btn_('200.000','set_nom:200000'),btn_('500.000','set_nom:500000'),btn_('1.000.000','set_nom:1000000')],
    [btn_('🧮 Keypad Angka','open_keypad'),btn_('✏️ Ketik Manual','prompt_custom_nom')],
    [btn_('◀️ Kembali','set_saldo_back'),btn_('❌ Batal','btn_menu')]
  ]; }
  function keypadMenu_() { return [[btn_('1','pad_add:1'),btn_('2','pad_add:2'),btn_('3','pad_add:3')],[btn_('4','pad_add:4'),btn_('5','pad_add:5'),btn_('6','pad_add:6')],[btn_('7','pad_add:7'),btn_('8','pad_add:8'),btn_('9','pad_add:9')],[btn_('000','pad_add:000'),btn_('0','pad_add:0'),btn_('⌫ Hapus','pad_backspace')],[btn_('🧹 Reset','pad_clear'),btn_('✅ SELESAI','pad_submit')],[btn_('◀️ Quick Nominal','back_quick_nom')]]; }
  function keteranganMenu_() { return [[btn_('➖ Tanpa Keterangan (-)','set_ket:-')],[btn_('◀️ Kembali ke Nominal','back_quick_nom'),btn_('❌ Batal','btn_menu')]]; }
  function confirmMenu_() { return [[btn_('✅ SIMPAN SEKARANG','do_save_transaction')],[btn_('✏️ Ubah Nominal','change_nom'),btn_('✏️ Ubah Ket.','change_ket')],[btn_('❌ BATAL / MENU UTAMA','btn_menu')]]; }
  function editMenu_() { return [[btn_('👤 Person','edit_sel_person'),btn_('🏷️ Jenis','edit_sel_jenis')],[btn_('📁 Kategori','edit_sel_kategori'),btn_('💳 Dompet','edit_sel_saldo')],[btn_('💰 Nominal','edit_sel_nominal'),btn_('✏️ Ket.','edit_sel_ket')],[btn_('💾 SIMPAN PERUBAHAN','do_save_edited_tx')],[btn_('❌ BATAL','btn_recent_10')]]; }
  function filterMenu_() { return [[btn_('🧠 Pencarian Natural','filter_prompt_natural')],[btn_('📅 Filter Tanggal','filter_menu_date'),btn_('👤 Filter Person','filter_menu_person')],[btn_('🏷️ Filter Jenis','filter_menu_jenis'),btn_('💳 Filter Dompet','filter_menu_wallet')],[btn_('🔤 Cari Kata Kunci','filter_prompt_keyword'),btn_('📋 50 Terbaru','filter_run:all_50')],[btn_('◀️ Menu Utama','btn_menu')]]; }
  function saldoPersonMenu_() { return [[btn_('👥 Semua Person (Total Aset)','saldo_select:all')],[btn_('👤 Abi','saldo_select:Abi'),btn_('👤 Ummah','saldo_select:Ummah')],[btn_('👤 Dafiq','saldo_select:Dafiq'),btn_('👤 Laviska','saldo_select:Laviska')],[btn_('👤 Toko','saldo_select:Toko')],[btn_('◀️ Menu Utama','btn_menu')]]; }
  function userMapMenu_() { const rows=[];let row=[];DEFAULT_PERSONS.forEach(p=>{row.push(btn_('👤 '+p,'set_user_map:'+p));if(row.length===2){rows.push(row);row=[];}});if(row.length)rows.push(row);rows.push([btn_('🗑️ Hapus Default Mapping','set_user_map:clear')]);rows.push([btn_('◀️ Menu Utama','btn_menu')]);return rows; }

  function retryInternal_(fn,retries) {
    let err; for(let i=0;i<=Math.max(0,retries||0);i++){try{return fn();}catch(e){err=e;}} throw err;
  }
  function cacheKey_(chatId){ return 'lftg_tx_v3'; }
  function clearComputedCaches_(){
    try { CacheService.getScriptCache().removeAll(['lftg_tx_v3','lftg_balance_v1','lftg_stats_v1']); } catch (_) {}
  }
  function clearTxCache_(chatId){ clearComputedCaches_(); }
  function fastRecentTransactions_(limit){
    const ss=SpreadsheetApp.openById(getSSID()), sh=ss.getSheetByName(SHEET_NAME);
    if(!sh || sh.getLastRow()<2) return [];
    const n=Math.min(Math.max(1,Number(limit)||TX_FETCH_LIMIT),sh.getLastRow()-1);
    // Responses is kept newest-first by ResponseSortService, so only read the required top rows.
    const rows=sh.getRange(2,1,n,Math.min(23,sh.getLastColumn())).getValues();
    return rows.map(function(r){
      let d=r[1], ds='';
      if(Object.prototype.toString.call(d)==='[object Date]' && !isNaN(d)) ds=Utilities.formatDate(d,TZ,'dd/MM/yyyy');
      else ds=String(d||'');
      return normalizeTx_({timestamp:r[0],tanggal:ds,jenisTransaksi:r[2],nominal:r[3],kategoriPemasukan:r[4],kategoriPengeluaran:r[5],keterangan:r[6],jenisSaldo:r[7],sumberDana:r[8],tujuanDana:r[9],jenisTabungan:r[10],kategoriPerson:r[11],rincianTransaksi:r[12],sumberLayanan:r[13],id:r[18]});
    });
  }
  function transactions_(chatId,limit){
    const cache=CacheService.getScriptCache(); let raw=null;
    try{raw=cache.get('lftg_tx_v3');}catch(_){}
    if(raw){try{return JSON.parse(raw).slice(0,limit||TX_FETCH_LIMIT);}catch(_){}}
    const list=fastRecentTransactions_(TX_FETCH_LIMIT);
    try{const json=JSON.stringify(list);if(json.length<95000)cache.put('lftg_tx_v3',json,CACHE_TTL);}catch(_){}
    return list.slice(0,limit||TX_FETCH_LIMIT);
  }
  function normalizeTx_(t) {
    t=t||{}; const jenis=t.jenis||t.jenisTransaksi||'Pengeluaran'; let cat=t.kategoriPilihan||'';
    if(!cat){if(jenis==='Pengeluaran')cat=t.kategoriPengeluaran||'';else if(jenis==='Pemasukan')cat=t.kategoriPemasukan||'';else if(jenis==='Pemindahan Saldo')cat='Pemindahan Saldo';else if(jenis==='Investasi dan Tabungan')cat=t.jenisTabungan||'';}
    const s=t.sumberDana||t.jenisSaldo||'Cash';
    return { id:String(t.id||t.ID||t.timestamp||''), tanggal:String(t.tanggal||fmtDate_()), jenis:jenis, kategoriPerson:String(t.kategoriPerson||'Abi'), kategoriPilihan:String(cat||'Lainnya'), jenisSaldo:String(s), sumberDana:String(s), tujuanDana:String(t.tujuanDana||t.jenisSaldoTujuan||''), sumberLayanan:String(t.sumberLayanan||t.tujuanPerson||''), nominal:Number(t.nominal)||0, keterangan:String(t.keterangan||'-') };
  }
  function findTxById_(chatId,id){ const txs=transactions_(chatId,TX_FETCH_LIMIT); return txs.find(t=>String(t.id)===String(id))||null; }
  function txCard_(t,index){ const prefix=index!=null?'<b>'+index+'.</b> ':''; if(t.jenis==='Pemindahan Saldo'){const p2=t.sumberLayanan||t.kategoriPerson,pstr=p2===t.kategoriPerson?t.kategoriPerson:t.kategoriPerson+' ➡️ '+p2;return prefix+'🔄 <b>'+esc_(t.tanggal)+'</b>  [<b>'+esc_(pstr)+'</b>]\n  💵 <b>'+rupiah_(t.nominal)+'</b>\n  🔄 <b>'+esc_(t.sumberDana)+'</b> ➡️ <b>'+esc_(t.tujuanDana||'-')+'</b>\n  📝 '+esc_(t.keterangan)+'\n  🔑 <code>'+esc_(t.id)+'</code>';}
    const icon=t.jenis==='Pengeluaran'?'🔴':t.jenis==='Pemasukan'?'🟢':'📈'; return prefix+icon+' <b>'+esc_(t.tanggal)+'</b>  [<b>'+esc_(t.kategoriPerson)+'</b>]\n  💵 <b>'+rupiah_(t.nominal)+'</b>  🏦 '+esc_(t.jenisSaldo)+'\n  🏷️ '+esc_(t.kategoriPilihan)+'  📝 '+esc_(t.keterangan)+'\n  🔑 <code>'+esc_(t.id)+'</code>';
  }
  function editSummary_(t){return '<b>✏️ EDIT TRANSAKSI</b>\n━━━━━━━━━━━━━━━━━━━━\n👤 <b>Person   :</b> '+esc_(t.kategoriPerson||'-')+'\n🏷️ <b>Jenis    :</b> '+esc_(t.jenis||'-')+'\n📁 <b>Kategori :</b> '+esc_(t.kategoriPilihan||'-')+'\n💳 <b>Dompet   :</b> '+esc_(t.jenisSaldo||'-')+'\n💰 <b>Nominal  :</b> '+rupiah_(t.nominal||0)+'\n✏️ <b>Ket.     :</b> '+esc_(t.keterangan||'-')+'\n━━━━━━━━━━━━━━━━━━━━\nPilih field yang ingin diubah:';}

  function renderBalance_(byPerson,personKey){
    const ts='🕐 <i>Update: '+Utilities.formatDate(now_(),TZ,'dd/MM/yyyy HH:mm')+'</i>'; byPerson=byPerson||{};
    if(personKey==='all'){
      let totalKas=0,totalTab=0; const summaries=[],wallets={},inv={};
      Object.keys(byPerson).forEach(p=>{const d=byPerson[p]||{}, bs=d.bySaldo||{}, iv=d.investasi||{};let kas=0,tab=0;Object.keys(bs).forEach(k=>{if(['Kartu Kredit','P & L','Penyesuaian'].indexOf(k)<0)kas+=Number(bs[k])||0;if(['P & L','Penyesuaian'].indexOf(k)<0)wallets[k]=(wallets[k]||0)+(Number(bs[k])||0);});Object.keys(iv).forEach(k=>{tab+=Number(iv[k])||0;inv[k]=(inv[k]||0)+(Number(iv[k])||0);});totalKas+=kas;totalTab+=tab;summaries.push('• <b>'+esc_(p)+'</b>: '+rupiah_(kas)+' + 📈'+rupiah_(tab)+' = <b>'+rupiah_(kas+tab)+'</b>');});
      const lines=['👥 <b>RINGKASAN SALDO KESELURUHAN</b>',ts,'━━━━━━━━━━━━━━━━━━━━','<b>👤 Total Aset per Person:</b>'].concat(summaries);
      if(Object.keys(wallets).length){lines.push('\n💳 <b>Total Saldo Kas per Dompet:</b>');Object.keys(wallets).sort((a,b)=>wallets[b]-wallets[a]).forEach(k=>{if(wallets[k])lines.push('  • <b>'+esc_(k)+'</b>: '+rupiah_(wallets[k]));});}
      if(Object.keys(inv).length){lines.push('\n📈 <b>Total Tabungan & Investasi:</b>');Object.keys(inv).sort((a,b)=>inv[b]-inv[a]).forEach(k=>{if(inv[k])lines.push('  • <b>'+esc_(k)+'</b>: '+rupiah_(inv[k]));});}
      lines.push('━━━━━━━━━━━━━━━━━━━━','💵 <b>TOTAL KAS     :</b> '+rupiah_(totalKas),'🪙 <b>TOTAL TABUNGAN:</b> '+rupiah_(totalTab),'💎 <b>TOTAL KEKAYAAN: '+rupiah_(totalKas+totalTab)+'</b>'); return lines.join('\n');
    }
    const d=byPerson[personKey]||{},bs=d.bySaldo||{},iv=d.investasi||{};let kas=0,tab=0;const kl=[],il=[];Object.keys(bs).sort((a,b)=>bs[b]-bs[a]).forEach(k=>{const v=Number(bs[k])||0;if(['P & L','Penyesuaian'].indexOf(k)<0&&v){kl.push('  • <b>'+esc_(k)+'</b>: '+rupiah_(v));if(k!=='Kartu Kredit')kas+=v;}});Object.keys(iv).sort((a,b)=>iv[b]-iv[a]).forEach(k=>{const v=Number(iv[k])||0;if(v){il.push('  • <b>'+esc_(k)+'</b>: '+rupiah_(v));tab+=v;}});
    return ['👤 <b>SALDO — '+esc_(personKey.toUpperCase())+'</b>',ts,'━━━━━━━━━━━━━━━━━━━━','💳 <b>SALDO KAS & DOMPET:</b>'].concat(kl.length?kl:['  • <i>Belum ada saldo kas</i>']).concat(['  └ Subtotal Kas: <b>'+rupiah_(kas)+'</b>\n','📈 <b>TABUNGAN & INVESTASI:</b>']).concat(il.length?il:['  • <i>Belum ada tabungan/investasi</i>']).concat(['  └ Subtotal: <b>'+rupiah_(tab)+'</b>\n','━━━━━━━━━━━━━━━━━━━━','💵 <b>TOTAL KAS     :</b> '+rupiah_(kas),'🪙 <b>TOTAL TABUNGAN:</b> '+rupiah_(tab),'💎 <b>TOTAL ASET '+esc_(personKey.toUpperCase())+': '+rupiah_(kas+tab)+'</b>']).join('\n');
  }

  function executeFilter_(chatId,type,val,page){
    const s=getSession_(chatId);s.filter_state={type:type,val:val||''};saveSession_(chatId,s);progress_(chatId,'🔍 MEMUAT & FILTER TRANSAKSI',['Mengambil data transaksi...','Menerapkan filter...']);
    const all=transactions_(chatId,TX_FETCH_LIMIT); const now=now_(),today=fmtDate_(now),yd=fmtDate_(new Date(now.getTime()-86400000)); const curMY=Utilities.formatDate(now,TZ,'MM/yyyy'); const first=new Date(now.getFullYear(),now.getMonth(),1,12),prev=new Date(first.getTime()-86400000),prevMY=Utilities.formatDate(prev,TZ,'MM/yyyy'); const wd=(now.getDay()+6)%7,weekStart=new Date(now.getTime()-wd*86400000); weekStart.setHours(0,0,0,0);
    let matched=[],title='';
    if(type==='date_today'){matched=all.filter(t=>t.tanggal===today);title='HARI INI ('+today+')';}
    else if(type==='date_yesterday'){matched=all.filter(t=>t.tanggal===yd);title='KEMARIN ('+yd+')';}
    else if(type==='date_week'){matched=all.filter(t=>{const d=parseDate_(t.tanggal);return d&&d>=weekStart&&d<=now;});title='MINGGU INI ('+Utilities.formatDate(weekStart,TZ,'dd/MM')+' – '+today+')';}
    else if(type==='date_month'){matched=all.filter(t=>String(t.tanggal).endsWith(curMY));title='BULAN INI ('+curMY+')';}
    else if(type==='date_prevmonth'){matched=all.filter(t=>String(t.tanggal).endsWith(prevMY));title='BULAN LALU ('+prevMY+')';}
    else if(type==='custom_date'){matched=all.filter(t=>String(t.tanggal).trim()===String(val).trim());title='TANGGAL '+val;}
    else if(type==='date_range'){const ps=String(val||'').toLowerCase().replace(/s\/d|sampai|to/g,'-').split('-').map(x=>x.trim()).filter(Boolean);let d1=ps[0]&&parseDate_(ps[0]),d2=ps[1]&&parseDate_(ps[1]);if(d1&&d2){if(d1>d2){const x=d1;d1=d2;d2=x;}matched=all.filter(t=>{const d=parseDate_(t.tanggal);return d&&d>=d1&&d<=d2;});title='RENTANG ('+fmtDate_(d1)+' s/d '+fmtDate_(d2)+')';}else title='RENTANG TANGGAL TIDAK VALID';}
    else if(type==='person'){matched=all.filter(t=>String(t.kategoriPerson).toLowerCase()===String(val).toLowerCase());title='PERSON: '+String(val).toUpperCase();}
    else if(type==='jenis'){matched=all.filter(t=>String(t.jenis).toLowerCase().indexOf(String(val).toLowerCase())>=0);title='JENIS: '+String(val).toUpperCase();}
    else if(type==='wallet'){matched=all.filter(t=>[t.jenisSaldo,t.sumberDana].some(x=>String(x).toLowerCase()===String(val).toLowerCase()));title='DOMPET: '+String(val).toUpperCase();}
    else if(type==='keyword'){const q=String(val).toLowerCase();matched=all.filter(t=>[t.kategoriPilihan,t.kategoriPerson,t.keterangan,t.jenisSaldo,t.sumberDana,t.tujuanDana,t.jenis,String(t.nominal)].some(x=>String(x).toLowerCase().indexOf(q)>=0));title='KATA KUNCI: «'+val+'»';}
    else{matched=all.slice(0,50);title='50 TRANSAKSI TERBARU';}
    const pages=Math.max(1,Math.ceil(matched.length/TX_PER_PAGE));page=Math.max(1,Math.min(Number(page)||1,pages));const start=(page-1)*TX_PER_PAGE,items=matched.slice(start,start+TX_PER_PAGE);const masuk=matched.filter(t=>t.jenis==='Pemasukan').reduce((a,t)=>a+t.nominal,0),keluar=matched.filter(t=>t.jenis==='Pengeluaran').reduce((a,t)=>a+t.nominal,0),net=masuk-keluar;
    const lines=['<b>🔍 FILTER — '+esc_(title)+'</b>','━━━━━━━━━━━━━━━━━━━━','📊 '+matched.length+' transaksi  |  Hal '+page+'/'+pages,'🟢 Masuk  : '+rupiah_(masuk),'🔴 Keluar : '+rupiah_(keluar),(net>=0?'🟢':'🔴')+' Net     : <b>'+rupiah_(net)+'</b>','━━━━━━━━━━━━━━━━━━━━\n']; const rows=[];
    items.forEach((t,i)=>{lines.push(txCard_(t,start+i+1),'');const ic=t.jenis==='Pengeluaran'?'🔴':t.jenis==='Pemasukan'?'🟢':'🔄';rows.push([btn_((start+i+1)+'. '+ic+' '+rupiah_(t.nominal)+' – '+String(t.kategoriPilihan||t.jenis).slice(0,22),'tx_view:'+t.id)]);}); if(!items.length)lines.push('ℹ️ <i>Tidak ada transaksi yang sesuai filter.</i>'); if(pages>1)rows.push([btn_('⬅️ Prev','filter_page:'+(page>1?page-1:pages)),btn_('📄 '+page+'/'+pages,'noop'),btn_('Next ➡️','filter_page:'+(page<pages?page+1:1))]); rows.push([btn_('🔍 Filter Lain','btn_filter_menu'),btn_('◀️ Menu Utama','btn_menu')]); sendOrEdit_(chatId,lines.join('\n'),rows);
  }

  function showRecent_(chatId){progress_(chatId,'📜 MEMUAT TRANSAKSI TERAKHIR',['Mengambil 10 transaksi terbaru...']);const txs=transactions_(chatId,10),lines=['<b>📋 10 TRANSAKSI TERAKHIR</b>','━━━━━━━━━━━━━━━━━━━━\n'],rows=[];if(txs.length){txs.forEach((t,i)=>{lines.push(txCard_(t,i+1),'');const ic=t.jenis==='Pengeluaran'?'🔴':t.jenis==='Pemasukan'?'🟢':'🔄';rows.push([btn_((i+1)+'. '+ic+' '+rupiah_(t.nominal)+' – '+String(t.kategoriPilihan||t.jenis).slice(0,22),'tx_view:'+t.id)]);});rows.push([btn_('➕ Catat Baru','wizard_start'),btn_('🔍 Filter & Cari','btn_filter_menu')]);rows.push([btn_('◀️ Menu Utama','btn_menu')]);}else{lines.push('ℹ️ <b>Belum ada transaksi tercatat.</b>');rows.push([btn_('➕ Catat Transaksi Baru','wizard_start')],[btn_('◀️ Menu Utama','btn_menu')]);}sendOrEdit_(chatId,lines.join('\n'),rows);}

  function showBalance_(chatId,personKey){
    const cache=CacheService.getScriptCache(); let res=null;
    try{const raw=cache.get('lftg_balance_v1');if(raw)res=JSON.parse(raw);}catch(_){}
    if(!res){res=calculateBalance();try{cache.put('lftg_balance_v1',JSON.stringify(res),30);}catch(_){}}
    const text=res&&res.byPerson?renderBalance_(res.byPerson,personKey):'❌ <b>Gagal memuat saldo.</b>';
    sendOrEdit_(chatId,text,[[btn_('👤 Pilih Person Lain','btn_cek_saldo'),btn_('🔄 Refresh','saldo_select:'+personKey)],[btn_('◀️ Menu Utama','btn_menu')]]);
  }

  const UNDO_WINDOW_MS = 60 * 1000;
  function numProp_(name,fallback){
    const n=Number(props_().getProperty(name));
    return Number.isFinite(n) && n >= 0 ? n : Number(fallback || 0);
  }
  function expenseRisk_(s){
    const out={large:false,low:false,threshold:numProp_('LAVI_FINANCE_TELEGRAM_LARGE_EXPENSE_THRESHOLD',500000),lowThreshold:numProp_('LAVI_FINANCE_TELEGRAM_LOW_BALANCE_THRESHOLD',100000),balance:null,remaining:null,messages:[]};
    if(!s || String(s.jenis)!=='Pengeluaran') return out;
    const nominal=Number(s.nominal)||0;
    if(nominal>=out.threshold){out.large=true;out.messages.push('Nominal '+rupiah_(nominal)+' melewati batas peringatan '+rupiah_(out.threshold)+'.');}
    const wallet=String(s.saldo||'').trim();
    if(wallet && ['Kartu Kredit','Penyesuaian','P & L'].indexOf(wallet)<0){
      try{
        const b=calculateBalance(), person=b&&b.byPerson&&b.byPerson[s.person], by=person&&person.bySaldo||{};
        if(Object.prototype.hasOwnProperty.call(by,wallet)){
          out.balance=Number(by[wallet])||0;out.remaining=out.balance-nominal;
          if(out.remaining<out.lowThreshold){out.low=true;out.messages.push('Perkiraan saldo '+wallet+' setelah transaksi: '+rupiah_(out.remaining)+' (batas rendah '+rupiah_(out.lowThreshold)+').');}
        }
      }catch(_){}
    }
    return out;
  }
  function sensitiveSaveText_(s,risk){
    const lines=['<b>🛡️ KONFIRMASI AKSI SENSITIF</b>','━━━━━━━━━━━━━━━━━━━━'];
    if(s && s.jenis==='Pemindahan Saldo') lines.push('🔄 Pemindahan saldo akan mengubah saldo asal dan tujuan.');
    (risk&&risk.messages||[]).forEach(m=>lines.push('🚨 '+esc_(m)));
    lines.push('',confirmationText_(s),'','<b>Lanjutkan penyimpanan?</b>');
    return lines.join('\n');
  }
  function undoInfo_(s){
    const at=Number(s&&s.last_transaction_at||0),id=String(s&&s.last_transaction_id||'');
    const age=at?Date.now()-at:Number.POSITIVE_INFINITY;
    return {id:id,at:at,age:age,valid:!!id&&age>=0&&age<=UNDO_WINDOW_MS,remaining:Math.max(0,UNDO_WINDOW_MS-age)};
  }
  function performUndo_(chatId){
    const s=getSession_(chatId),u=undoInfo_(s);
    if(!u.valid){
      delete s.last_transaction_id;delete s.last_transaction_at;saveSession_(chatId,s);
      sendOrEdit_(chatId,'⏱️ <b>Waktu pembatalan sudah berakhir.</b>\nTransaksi hanya dapat dibatalkan maksimal 1 menit setelah dibuat.',[[btn_('📜 10 Transaksi Terakhir','btn_recent_10')],[btn_('◀️ Menu Utama','btn_menu')]]);return;
    }
    let res;try{res=deleteTransaction(u.id);}catch(e){res={success:false,message:String(e)}}
    clearTxCache_(chatId);
    if(res&&res.success){delete s.last_transaction_id;delete s.last_transaction_at;delete s.last_payload;saveSession_(chatId,s);sendOrEdit_(chatId,'<b>↩️ TRANSAKSI BERHASIL DIBATALKAN</b>\n━━━━━━━━━━━━━━━━━━━━\n🆔 <code>'+esc_(u.id)+'</code>\nData transaksi dihapus dan saldo akan mengikuti data terbaru.',[[btn_('➕ Catat Baru','wizard_start'),btn_('📜 Riwayat','btn_recent_10')],[btn_('◀️ Menu Utama','btn_menu')]]);}else sendOrEdit_(chatId,'❌ <b>Gagal membatalkan transaksi.</b>\n'+esc_(res&&res.message||'Transaksi tidak dapat dihapus.'),[[btn_('◀️ Menu Utama','btn_menu')]]);
  }
  function saveEditedTx_(chatId){
    const s=getSession_(chatId),t=s.editing_tx;if(!t)return;
    const j=t.jenis||'Pengeluaran',c=t.kategoriPilihan||'';
    const raw=Object.assign({},t,{jenisTransaksi:j,kategoriPemasukan:j==='Pemasukan'?c:'',kategoriPengeluaran:j==='Pengeluaran'?c:'',jenisTabungan:j==='Investasi dan Tabungan'?c:'',sumberDana:t.jenisSaldo||'Cash'});
    let res;try{res=editTransaction(raw);}catch(e){res={success:false,message:String(e)}}
    clearTxCache_(chatId);
    sendOrEdit_(chatId,res&&res.success?'<b>✅ PERUBAHAN BERHASIL DISIMPAN!</b>\n━━━━━━━━━━━━━━━━━━━━\n📁 '+esc_(c)+' | '+rupiah_(t.nominal):'❌ <b>Gagal Menyimpan Perubahan!</b>\nAlasan: '+esc_(res&&res.message||'Gagal'),[[btn_('📜 Kembali ke Daftar','btn_recent_10')],[btn_('◀️ Menu Utama','btn_menu')]]);
  }

  function allTransactions_(){
    return fetchRecentTransactions().map(normalizeTx_);
  }
  function monthKey_(d){return d?Utilities.formatDate(d,TZ,'yyyy-MM'):'';}
  function aggregateTx_(list){
    const out={count:0,income:0,expense:0,net:0,categories:{}};
    (list||[]).forEach(t=>{const n=Number(t.nominal)||0;out.count++;if(t.jenis==='Pemasukan')out.income+=n;if(t.jenis==='Pengeluaran'||t.jenis==='Cicilan dan Angsuran'){out.expense+=n;out.categories[t.kategoriPilihan||'Lainnya']=(out.categories[t.kategoriPilihan||'Lainnya']||0)+n;}});out.net=out.income-out.expense;return out;
  }
  function pctText_(current,previous){
    current=Number(current)||0;previous=Number(previous)||0;if(previous===0)return current===0?'0%':'baru';const p=((current-previous)/Math.abs(previous))*100;return (p>0?'+':'')+p.toFixed(1)+'%';
  }
  function showMonthlyDashboard_(chatId){
    const cache=CacheService.getScriptCache(),now=now_(),key='lftg_monthdash_'+Utilities.formatDate(now,TZ,'yyyyMM');let data=null;
    try{const raw=cache.get(key);if(raw)data=JSON.parse(raw);}catch(_){}
    if(!data){
      const currentKey=monthKey_(now),first=new Date(now.getFullYear(),now.getMonth(),1,12),prevDate=new Date(first.getTime()-86400000),prevKey=monthKey_(prevDate),all=allTransactions_();
      const cur=[],prev=[];all.forEach(t=>{const d=parseDate_(t.tanggal),k=monthKey_(d);if(k===currentKey)cur.push(t);else if(k===prevKey)prev.push(t);});
      data={current:aggregateTx_(cur),previous:aggregateTx_(prev),currentLabel:BULAN[now.getMonth()]+' '+now.getFullYear(),previousLabel:BULAN[prevDate.getMonth()]+' '+prevDate.getFullYear()};
      try{cache.put(key,JSON.stringify(data),120);}catch(_){}
    }
    const c=data.current,p=data.previous,top=Object.keys(c.categories||{}).map(k=>({name:k,total:c.categories[k]})).sort((a,b)=>b.total-a.total).slice(0,3);
    const lines=['<b>📊 DASHBOARD BULAN INI</b>','━━━━━━━━━━━━━━━━━━━━','🗓️ <b>'+esc_(data.currentLabel)+'</b>','📋 Transaksi: <b>'+c.count+'</b>','🟢 Pemasukan: <b>'+rupiah_(c.income)+'</b>','🔴 Pengeluaran: <b>'+rupiah_(c.expense)+'</b>',(c.net>=0?'🟢':'🔴')+' Net: <b>'+rupiah_(c.net)+'</b>'];
    if(top.length){lines.push('','<b>🏆 Pengeluaran Terbesar:</b>');top.forEach((x,i)=>lines.push((i+1)+'. '+esc_(x.name)+' — <b>'+rupiah_(x.total)+'</b>'));}
    lines.push('','<b>↔️ Dibanding '+esc_(data.previousLabel)+':</b>','• Pemasukan: '+pctText_(c.income,p.income),'• Pengeluaran: '+pctText_(c.expense,p.expense),'• Net: '+pctText_(c.net,p.net),'━━━━━━━━━━━━━━━━━━━━');
    sendOrEdit_(chatId,lines.join('\n'),[[btn_('📄 Export Bulan Ini','export_scope:month'),btn_('🔄 Refresh','btn_dashboard_month')],[btn_('💰 Cek Saldo','btn_cek_saldo'),btn_('◀️ Menu Utama','btn_menu')]]);
  }
  function parseNatural_(query){
    const raw=String(query||'').trim(),q=raw.toLowerCase();const spec={raw:raw,jenis:'',person:'',date:'',wallet:'',keyword:''};
    if(/\b(pengeluaran|keluar|belanja)\b/.test(q))spec.jenis='Pengeluaran';else if(/\b(pemasukan|masuk|pendapatan)\b/.test(q))spec.jenis='Pemasukan';else if(/\b(investasi|tabungan)\b/.test(q))spec.jenis='Investasi dan Tabungan';else if(/\b(transfer|pemindahan)\b/.test(q))spec.jenis='Pemindahan Saldo';
    DEFAULT_PERSONS.forEach(p=>{if(!spec.person&&q.indexOf(p.toLowerCase())>=0)spec.person=p;});
    if(q.indexOf('hari ini')>=0)spec.date='today';else if(q.indexOf('kemarin')>=0)spec.date='yesterday';else if(q.indexOf('minggu ini')>=0)spec.date='week';else if(q.indexOf('bulan lalu')>=0)spec.date='prevmonth';else if(q.indexOf('bulan ini')>=0)spec.date='month';
    wallets_().slice().sort((a,b)=>b.length-a.length).forEach(w=>{if(!spec.wallet&&q.indexOf(String(w).toLowerCase())>=0)spec.wallet=w;});
    let rest=q.replace(/hari ini|kemarin|minggu ini|bulan ini|bulan lalu/g,' ').replace(/\b(pengeluaran|keluar|belanja|pemasukan|masuk|pendapatan|investasi|tabungan|transfer|pemindahan|transaksi|cari|carikan|tampilkan|lihat|semua|untuk|yang|dari|di)\b/g,' ');
    DEFAULT_PERSONS.forEach(p=>{rest=rest.replace(new RegExp('\\b'+p.toLowerCase()+'\\b','g'),' ');});
    wallets_().forEach(w=>{rest=rest.split(String(w).toLowerCase()).join(' ');});
    spec.keyword=rest.replace(/\s+/g,' ').trim();return spec;
  }
  function naturalMatches_(t,spec){
    if(spec.jenis&&String(t.jenis).toLowerCase().indexOf(spec.jenis.toLowerCase())<0)return false;
    if(spec.person&&String(t.kategoriPerson).toLowerCase()!==spec.person.toLowerCase())return false;
    if(spec.wallet&&![t.jenisSaldo,t.sumberDana,t.tujuanDana].some(x=>String(x).toLowerCase()===spec.wallet.toLowerCase()))return false;
    const d=parseDate_(t.tanggal),now=now_();
    if(spec.date&&d){
      if(spec.date==='today'&&fmtDate_(d)!==fmtDate_(now))return false;
      if(spec.date==='yesterday'&&fmtDate_(d)!==fmtDate_(new Date(now.getTime()-86400000)))return false;
      if(spec.date==='month'&&monthKey_(d)!==monthKey_(now))return false;
      if(spec.date==='prevmonth'){const first=new Date(now.getFullYear(),now.getMonth(),1,12),prev=new Date(first.getTime()-86400000);if(monthKey_(d)!==monthKey_(prev))return false;}
      if(spec.date==='week'){const wd=(now.getDay()+6)%7,start=new Date(now.getTime()-wd*86400000);start.setHours(0,0,0,0);if(d<start||d>now)return false;}
    }
    if(spec.keyword){const words=spec.keyword.split(/\s+/).filter(Boolean),hay=[t.kategoriPilihan,t.kategoriPerson,t.keterangan,t.jenisSaldo,t.sumberDana,t.tujuanDana,t.jenis,String(t.nominal)].join(' ').toLowerCase();if(!words.every(w=>hay.indexOf(w)>=0))return false;}
    return true;
  }
  function executeNaturalSearch_(chatId,query,page){
    const s=getSession_(chatId),spec=parseNatural_(query);s.filter_state={type:'natural',val:String(query||'')};saveSession_(chatId,s);
    const matched=allTransactions_().filter(t=>naturalMatches_(t,spec)),pages=Math.max(1,Math.ceil(matched.length/TX_PER_PAGE));page=Math.max(1,Math.min(Number(page)||1,pages));const start=(page-1)*TX_PER_PAGE,items=matched.slice(start,start+TX_PER_PAGE),a=aggregateTx_(matched);
    const tags=[];if(spec.jenis)tags.push(spec.jenis);if(spec.person)tags.push(spec.person);if(spec.date)tags.push(spec.date);if(spec.wallet)tags.push(spec.wallet);if(spec.keyword)tags.push('“'+spec.keyword+'”');
    const lines=['<b>🧠 PENCARIAN NATURAL</b>','━━━━━━━━━━━━━━━━━━━━','🔎 '+esc_(query),'🎯 '+esc_(tags.join(' • ')||'Semua transaksi'),'📊 <b>'+matched.length+'</b> hasil | Hal '+page+'/'+pages,'🟢 '+rupiah_(a.income)+'  🔴 '+rupiah_(a.expense),'━━━━━━━━━━━━━━━━━━━━\n'];const rows=[];
    items.forEach((t,i)=>{lines.push(txCard_(t,start+i+1),'');rows.push([btn_((start+i+1)+'. '+rupiah_(t.nominal)+' — '+String(t.kategoriPilihan).slice(0,24),'tx_view:'+t.id)]);});if(!items.length)lines.push('ℹ️ Tidak ada transaksi yang cocok.');if(pages>1)rows.push([btn_('⬅️ Prev','filter_page:'+(page>1?page-1:pages)),btn_('📄 '+page+'/'+pages,'noop'),btn_('Next ➡️','filter_page:'+(page<pages?page+1:1))]);rows.push([btn_('🧠 Cari Lagi','filter_prompt_natural'),btn_('◀️ Menu Utama','btn_menu')]);sendOrEdit_(chatId,lines.join('\n'),rows);
  }
  function exportScopeMenu_(){return [[btn_('📅 Hari Ini','export_scope:today'),btn_('🗓️ Bulan Ini','export_scope:month')],[btn_('🗓️ Bulan Lalu','export_scope:prevmonth'),btn_('📚 Semua Data','export_scope:all')],[btn_('👤 Per Person','export_scope_person'),btn_('📆 Rentang Tanggal','export_scope_range')],[btn_('◀️ Menu Utama','btn_menu')]];}
  function showExportFormat_(chatId,spec,label){const s=getSession_(chatId);s.export_spec=spec;saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📄 EXPORT TRANSAKSI</b>\n━━━━━━━━━━━━━━━━━━━━\nCakupan: <b>'+esc_(label)+'</b>\n\nPilih format file:',[[btn_('📗 Excel (.xlsx)','export_do:xlsx'),btn_('📕 PDF','export_do:pdf')],[btn_('◀️ Ganti Cakupan','btn_export'),btn_('🏠 Menu','btn_menu')]]);}
  function filterExport_(all,spec){
    spec=spec||{type:'all'};const now=now_();return (all||[]).filter(t=>{const d=parseDate_(t.tanggal);if(spec.type==='all')return true;if(spec.type==='today')return d&&fmtDate_(d)===fmtDate_(now);if(spec.type==='month')return d&&monthKey_(d)===monthKey_(now);if(spec.type==='prevmonth'){const first=new Date(now.getFullYear(),now.getMonth(),1,12),prev=new Date(first.getTime()-86400000);return d&&monthKey_(d)===monthKey_(prev);}if(spec.type==='person')return String(t.kategoriPerson)===String(spec.person);if(spec.type==='range'){const a=parseDate_(spec.start),b=parseDate_(spec.end);return d&&a&&b&&d>=a&&d<=b;}return true;});
  }
  function xmlEsc_(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
  function colName_(n){let s='';while(n>0){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
  function buildXlsx_(txs,fileName){
    const headers=['No','Tanggal','Jenis','Person','Kategori','Dompet/Sumber','Tujuan','Nominal','Keterangan','ID'];
    const rows=[headers].concat((txs||[]).map((t,i)=>[i+1,t.tanggal,t.jenis,t.kategoriPerson,t.kategoriPilihan,t.jenisSaldo||t.sumberDana,t.tujuanDana||'',Number(t.nominal)||0,t.keterangan,t.id]));
    const sheetRows=rows.map((row,ri)=>'<row r="'+(ri+1)+'">'+row.map((v,ci)=>{const ref=colName_(ci+1)+(ri+1);if(ri>0&&(ci===0||ci===7))return '<c r="'+ref+'" s="'+(ci===7?2:0)+'" t="n"><v>'+Number(v||0)+'</v></c>';return '<c r="'+ref+'"'+(ri===0?' s="1"':'')+' t="inlineStr"><is><t>'+xmlEsc_(v)+'</t></is></c>';}).join('')+'</row>').join('');
    const sheet='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="1" width="7" customWidth="1"/><col min="2" max="2" width="14" customWidth="1"/><col min="3" max="7" width="22" customWidth="1"/><col min="8" max="8" width="16" customWidth="1"/><col min="9" max="9" width="38" customWidth="1"/><col min="10" max="10" width="18" customWidth="1"/></cols><sheetData>'+sheetRows+'</sheetData><autoFilter ref="A1:J'+rows.length+'"/></worksheet>';
    const parts=[
      Utilities.newBlob('<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>','application/xml','[Content_Types].xml'),
      Utilities.newBlob('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','application/xml','_rels/.rels'),
      Utilities.newBlob('<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Transaksi" sheetId="1" r:id="rId1"/></sheets></workbook>','application/xml','xl/workbook.xml'),
      Utilities.newBlob('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>','application/xml','xl/_rels/workbook.xml.rels'),
      Utilities.newBlob('<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Arial"/></font><font><b/><sz val="11"/><name val="Arial"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/><xf numFmtId="3" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs></styleSheet>','application/xml','xl/styles.xml'),
      Utilities.newBlob(sheet,'application/xml','xl/worksheets/sheet1.xml')
    ];
    const zipped=Utilities.zip(parts,fileName);return Utilities.newBlob(zipped.getBytes(),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',fileName);
  }
  function ascii_(v){try{return String(v==null?'':v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'?');}catch(_){return String(v==null?'':v).replace(/[^\x20-\x7E]/g,'?');}}
  function pdfEsc_(v){return ascii_(v).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');}
  function buildPdf_(txs,fileName,title){
    const rows=(txs||[]).map((t,i)=>String(i+1).padStart(4,' ')+' | '+String(t.tanggal).padEnd(10,' ')+' | '+String(t.jenis).slice(0,15).padEnd(15,' ')+' | '+String(t.kategoriPerson).slice(0,8).padEnd(8,' ')+' | '+String(t.kategoriPilihan).slice(0,24).padEnd(24,' ')+' | '+String(Math.round(Number(t.nominal)||0)).padStart(12,' ')+' | '+String(t.id).slice(0,14));
    const perPage=47,pages=[];for(let i=0;i<Math.max(1,Math.ceil(rows.length/perPage));i++)pages.push(rows.slice(i*perPage,(i+1)*perPage));
    const objs={};objs[1]='<< /Type /Catalog /Pages 2 0 R >>';objs[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>';
    const kids=[];pages.forEach((lines,i)=>{const po=4+i*2,co=5+i*2;kids.push(po+' 0 R');const head=[ascii_(title||'Lavi Finance Export'),'Total transaksi: '+rows.length+' | Dibuat: '+Utilities.formatDate(now_(),TZ,'dd/MM/yyyy HH:mm'),'No   | Tanggal    | Jenis           | Person   | Kategori                 |      Nominal | ID','----------------------------------------------------------------------------------------------------------------'];const all=head.concat(lines);let content='BT\n/F1 7 Tf\n24 570 Td\n';all.forEach((line,j)=>{if(j>0)content+='0 -11 Td\n';content+='('+pdfEsc_(line.slice(0,128))+') Tj\n';});content+='ET\n';objs[co]='<< /Length '+content.length+' >>\nstream\n'+content+'endstream';objs[po]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 3 0 R >> >> /Contents '+co+' 0 R >>';});objs[2]='<< /Type /Pages /Kids ['+kids.join(' ')+'] /Count '+pages.length+' >>';
    const max=3+pages.length*2;let pdf='%PDF-1.4\n%LAVI\n',offs=[0];for(let i=1;i<=max;i++){offs[i]=pdf.length;pdf+=i+' 0 obj\n'+objs[i]+'\nendobj\n';}const xref=pdf.length;pdf+='xref\n0 '+(max+1)+'\n0000000000 65535 f \n';for(let i=1;i<=max;i++)pdf+=String(offs[i]).padStart(10,'0')+' 00000 n \n';pdf+='trailer\n<< /Size '+(max+1)+' /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';return Utilities.newBlob(pdf,'application/pdf',fileName);
  }
  function exportLabel_(spec){if(!spec)return 'Semua Data';if(spec.type==='today')return 'Hari Ini';if(spec.type==='month')return 'Bulan Ini';if(spec.type==='prevmonth')return 'Bulan Lalu';if(spec.type==='person')return 'Person '+spec.person;if(spec.type==='range')return spec.start+' s/d '+spec.end;return 'Semua Data';}
  function sendExport_(chatId,format){
    const s=getSession_(chatId),spec=s.export_spec||{type:'all'},txs=filterExport_(allTransactions_(),spec),stamp=Utilities.formatDate(now_(),TZ,'yyyyMMdd-HHmm'),base='Lavi-Finance-'+stamp;
    if(!txs.length){sendOrEdit_(chatId,'ℹ️ <b>Tidak ada data untuk diekspor.</b>',[[btn_('◀️ Pilih Cakupan','btn_export')],[btn_('🏠 Menu','btn_menu')]]);return;}
    const blob=format==='pdf'?buildPdf_(txs,base+'.pdf','Lavi Finance - '+exportLabel_(spec)):buildXlsx_(txs,base+'.xlsx');tgDocument_(chatId,blob,'Lavi Finance • '+exportLabel_(spec)+' • '+txs.length+' transaksi');sendOrEdit_(chatId,'✅ <b>EXPORT BERHASIL</b>\n━━━━━━━━━━━━━━━━━━━━\nFormat: <b>'+String(format).toUpperCase()+'</b>\nCakupan: <b>'+esc_(exportLabel_(spec))+'</b>\nTransaksi: <b>'+txs.length+'</b>',[[btn_('📄 Export Lain','btn_export')],[btn_('🏠 Menu','btn_menu')]]);
  }
  function safeFetchJson_(url){try{const r=UrlFetchApp.fetch(url,{muteHttpExceptions:true,followRedirects:true});if(r.getResponseCode()<200||r.getResponseCode()>=300)return null;return JSON.parse(r.getContentText());}catch(_){return null;}}
  function showSystemStatus_(chatId){
    let sheetOk=false,rows=0;try{const sh=SpreadsheetApp.openById(getSSID()).getSheetByName(SHEET_NAME);sheetOk=!!sh;rows=sh?Math.max(0,sh.getLastRow()-1):0;}catch(_){}
    const relay=safeFetchJson_('https://lavi-finance-new.latieftjm.workers.dev/healthz');
    const auto=safeFetchJson_('https://script.google.com/macros/s/AKfycbzQrSAkyYnhHfD-m9ccAP_YV9x18hA6IkxDC-E36x5NuQLG0KTf2IbEOhAlEIkvh0BP3w/exec?action=systemStatusSafe');
    let wh=null;try{wh=tg_('getWebhookInfo',{},0);}catch(_){}
    const sup=auto&&auto.supabase||{},bak=auto&&auto.backup||{},sort=auto&&auto.sort||{};
    const lines=['<b>🩺 STATUS SISTEM LAVI FINANCE</b>','━━━━━━━━━━━━━━━━━━━━','Backend GAS: <b>✅ Aktif</b>','Spreadsheet: <b>'+(sheetOk?'✅':'❌')+'</b> ('+rows+' transaksi)','Cloudflare Relay: <b>'+(relay&&relay.ok?'✅':'❌')+'</b>','Telegram Webhook: <b>'+(wh&&Number(wh.pending_update_count||0)===0&&!wh.last_error_message?'✅':'⚠️')+'</b> • pending '+Number(wh&&wh.pending_update_count||0),'Supabase Mirror: <b>'+(sup.status==='OK'?'✅ '+sup.status:(sup.status?'⚠️ '+esc_(sup.status):'ℹ️ belum tersedia'))+'</b>','Backup Harian: <b>'+((['SUCCESS','BERHASIL'].indexOf(bak.status)>=0)?'✅ '+bak.status:(bak.status?'⚠️ '+esc_(bak.status):'ℹ️ belum tersedia'))+'</b>'];
    if(sup.lastAt)lines.push('Sync/Audit terakhir: <code>'+esc_(sup.lastAt)+'</code>');if(bak.lastAt)lines.push('Backup terakhir: <code>'+esc_(bak.lastAt)+'</code>');if(sort.lastAt)lines.push('Sort Responses: <b>'+esc_(sort.status||'-')+'</b> • '+esc_(sort.lastAt));lines.push('━━━━━━━━━━━━━━━━━━━━','<i>Tidak ada token, chat ID, PIN, atau credential yang ditampilkan.</i>');
    sendOrEdit_(chatId,lines.join('\n'),[[btn_('🔄 Refresh Status','btn_system_status')],[btn_('◀️ Menu Utama','btn_menu')]]);
  }

  function confirmationText_(s){if(s.jenis==='Pemindahan Saldo')return '<b>✨ KONFIRMASI PEMINDAHAN SALDO</b>\n━━━━━━━━━━━━━━━━━━━━\n📅 Tanggal       : <b>'+esc_(s.tanggal)+'</b>\n👤 Person Asal    : <b>'+esc_(s.person)+'</b>\n💳 Dompet Asal    : <b>'+esc_(s.saldo_asal)+'</b>\n👥 Person Tujuan  : <b>'+esc_(s.person_tujuan)+'</b>\n🏦 Dompet Tujuan  : <b>'+esc_(s.saldo_tujuan)+'</b>\n💰 Nominal        : <b>'+rupiah_(s.nominal)+'</b>\n✏️ Keterangan     : <b>'+esc_(s.keterangan||'-')+'</b>\n━━━━━━━━━━━━━━━━━━━━\nApakah data transfer sudah benar?';return '<b>📝 KONFIRMASI SIMPAN TRANSAKSI</b>\n━━━━━━━━━━━━━━━━━━━━\n📅 Tanggal  : <b>'+esc_(s.tanggal)+'</b>\n👤 Person   : <b>'+esc_(s.person)+'</b>\n🏷️ Jenis    : <b>'+esc_(s.jenis)+'</b>\n📁 Kategori : <b>'+esc_(s.kategori)+'</b>\n💳 Dompet   : <b>'+esc_(s.saldo)+'</b>\n💰 Nominal  : <b>'+rupiah_(s.nominal)+'</b>\n✏️ Ket.     : <b>'+esc_(s.keterangan||'-')+'</b>\n━━━━━━━━━━━━━━━━━━━━\nApakah data sudah benar?';}

  function saveWizardTx_(chatId){const s=getSession_(chatId);progress_(chatId,'💾 MENYIMPAN TRANSAKSI',['Validasi data transaksi...','Menyimpan ke Google Sheets...','Memperbarui saldo...']);let payload;if(s.jenis==='Pemindahan Saldo'){let p2=s.person_tujuan||'';if(p2===s.person)p2='';payload={tanggal:s.tanggal,jenis:'Pemindahan Saldo',jenisTransaksi:'Pemindahan Saldo',kategoriPilihan:'Pemindahan Saldo',kategoriPerson:s.person,sumberLayanan:p2,rincianTransaksi:'Telegram',jenisSaldo:s.saldo_asal,sumberDana:s.saldo_asal,jenisSaldoTujuan:s.saldo_tujuan,tujuanDana:s.saldo_tujuan,nominal:s.nominal,keterangan:s.keterangan||'-',file:null,fileUploadMethod:'none'};}else{const j=s.jenis||'Pengeluaran',c=s.kategori||'';payload={tanggal:s.tanggal,jenis:j,jenisTransaksi:j,kategoriPerson:s.person,kategoriPilihan:c,kategoriPemasukan:j==='Pemasukan'?c:'',kategoriPengeluaran:j==='Pengeluaran'?c:'',jenisTabungan:j==='Investasi dan Tabungan'?c:'',jenisSaldo:s.saldo,sumberDana:s.saldo,nominal:s.nominal,keterangan:s.keterangan||'-',rincianTransaksi:'Telegram',sumberLayanan:'',file:null,fileUploadMethod:'none'};}
    let res;try{res=retryInternal_(function(){return saveTransaction(payload);},1);}catch(e){res={success:false,message:String(e)};}clearTxCache_(chatId);if(res&&res.success){const oldMsg=s.last_msg_id,last=payload;let text;if(payload.jenis==='Pemindahan Saldo')text='<b>✅ PEMINDAHAN SALDO BERHASIL!</b>\n━━━━━━━━━━━━━━━━━━━━\n📅 '+esc_(payload.tanggal)+'\n👤 '+esc_(payload.kategoriPerson)+' ('+esc_(payload.sumberDana)+') ➡️ '+esc_(payload.sumberLayanan||payload.kategoriPerson)+' ('+esc_(payload.tujuanDana)+')\n💰 <b>'+rupiah_(payload.nominal)+'</b>\n✏️ '+esc_(payload.keterangan)+'\n━━━━━━━━━━━━━━━━━━━━\nSaldo kedua dompet & person telah disesuaikan. ✨';else{text='<b>'+(payload.jenis==='Pengeluaran'?'🔴':'🟢')+' TRANSAKSI BERHASIL DISIMPAN!</b>\n━━━━━━━━━━━━━━━━━━━━\n📅 '+esc_(payload.tanggal)+'  |  👤 '+esc_(payload.kategoriPerson)+'\n📁 '+esc_(payload.kategoriPilihan)+'  |  💳 '+esc_(payload.jenisSaldo)+'\n💰 <b>'+rupiah_(payload.nominal)+'</b>\n✏️ '+esc_(payload.keterangan)+'\n━━━━━━━━━━━━━━━━━━━━\nData langsung tersimpan di Google Sheets. 🚀';}const ns={step:'MENU',last_msg_id:oldMsg,last_payload:last,last_transaction_id:String(res.id||''),last_transaction_at:Date.now(),_updatedAt:Date.now()};saveSession_(chatId,ns);sendOrEdit_(chatId,text,[[btn_('↩️ Batalkan (1 menit)','undo_last_tx')],[btn_('➕ Catat Lagi','wizard_start'),btn_('🔁 Ulangi Ini','wizard_repeat_last')],[btn_('📊 Hari Ini','btn_today_summary'),btn_('💰 Cek Saldo','btn_cek_saldo')],[btn_('◀️ Menu Utama','btn_menu')]]);}else{s.step='CONFIRMATION';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>❌ GAGAL MENYIMPAN TRANSAKSI</b>\n━━━━━━━━━━━━━━━━━━━━\nAlasan: <i>'+esc_(res&&res.message||'Koneksi gagal')+'</i>\n\nData dipertahankan — tekan <b>Coba Lagi</b>.',[[btn_('🔄 Coba Lagi','do_save_transaction')],[btn_('◀️ Menu Utama','btn_menu')]]);}}

  function handleCommand_(chatId,messageId,text){
    try{
      const cmd=String(text||'').split(/\s+/)[0].toLowerCase().split('@')[0];
      if(cmd==='/total'){const p=getMappedPerson_(chatId)||'all';showBalance_(chatId,p);return;}
      const s=getSession_(chatId);s.step='MENU';saveSession_(chatId,s);sendOrEdit_(chatId,menuText_(),mainMenu_());
    }finally{deleteMessage_(chatId,messageId);}
  }
  function handleText_(chatId,messageId,userText){const s=getSession_(chatId),step=s.step;try{
    if(step==='WAIT_SEARCH_KEYWORD'){s.step=null;saveSession_(chatId,s);executeFilter_(chatId,'keyword',userText,1);return;}
    if(step==='WAIT_NATURAL_SEARCH'){s.step='MENU';saveSession_(chatId,s);executeNaturalSearch_(chatId,userText,1);return;}
    if(step==='WAIT_EXPORT_DATERANGE'){const ps=String(userText).toLowerCase().replace(/s\/d|sampai|to/g,'-').split('-').map(x=>x.trim()).filter(Boolean),a=ps[0]&&parseDate_(ps[0]),b=ps[1]&&parseDate_(ps[1]);if(!a||!b){sendOrEdit_(chatId,'❌ Rentang tanggal tidak valid. Gunakan <code>dd/mm/yyyy - dd/mm/yyyy</code>',[[btn_('◀️ Batal','btn_export')]]);return;}const start=a<=b?a:b,end=a<=b?b:a;s.step='MENU';saveSession_(chatId,s);showExportFormat_(chatId,{type:'range',start:fmtDate_(start),end:fmtDate_(end)},fmtDate_(start)+' s/d '+fmtDate_(end));return;}
    if(step==='WAIT_FILTER_DATE'){s.step=null;saveSession_(chatId,s);executeFilter_(chatId,'custom_date',userText,1);return;}
    if(step==='WAIT_FILTER_DATERANGE'){s.step=null;saveSession_(chatId,s);executeFilter_(chatId,'date_range',userText,1);return;}
    if(step==='WAIT_TEXT_PERSON'){s.person=userText;s.step='SELECT_TYPE';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📝 TRANSAKSI BARU (2/6)</b>\n━━━━━━━━━━━━━━━━━━━━\n👤 Person : <b>'+esc_(userText)+'</b>\n\nPilih <b>Jenis Transaksi</b>:',typeMenu_(false));return;}
    if(step==='WAIT_TEXT_CATEGORY'){s.kategori=userText;s.step='SELECT_SALDO';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📝 TRANSAKSI BARU (4/6)</b>\n━━━━━━━━━━━━━━━━━━━━\n👤 Person   : <b>'+esc_(s.person)+'</b>\n🏷️ Jenis    : <b>'+esc_(s.jenis)+'</b>\n📁 Kategori : <b>'+esc_(userText)+'</b> <i>(Custom)</i>\n\nPilih <b>Dompet / Saldo</b>:',walletMenu_());return;}
    if(step==='WAIT_TEXT_NOMINAL'){const n=Number(String(userText).replace(/\D/g,''));if(!(n>0)){sendOrEdit_(chatId,'❌ <b>Nominal tidak valid.</b>\nMasukkan angka saja, contoh: <code>50000</code>',[[btn_('◀️ Batal','back_quick_nom')]]);return;}s.nominal=n;s.step='WAIT_TEXT_KETERANGAN';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📝 TRANSAKSI BARU (6/6)</b>\n━━━━━━━━━━━━━━━━━━━━\n👤 Person   : <b>'+esc_(s.person)+'</b>\n🏷️ Jenis    : <b>'+esc_(s.jenis)+'</b>\n📁 Kategori : <b>'+esc_(s.kategori)+'</b>\n💳 Dompet   : <b>'+esc_(s.saldo)+'</b>\n💰 Nominal  : <b>'+rupiah_(n)+'</b>\n\n✏️ <b>Ketik Keterangan Transaksi:</b>',keteranganMenu_());return;}
    if(step==='WAIT_TEXT_KETERANGAN'){s.keterangan=userText;s.step='CONFIRMATION';saveSession_(chatId,s);sendOrEdit_(chatId,confirmationText_(s),confirmMenu_());return;}
    if(step==='WAIT_TEXT_EDIT_NOMINAL'){const n=Number(String(userText).replace(/\D/g,''));if(!(n>0)){sendOrEdit_(chatId,'❌ Nominal tidak valid. Ketik angka nominal saja:',[[btn_('◀️ Batal','edit_back_to_summary')]]);return;}if(s.editing_tx)s.editing_tx.nominal=n;s.step=null;saveSession_(chatId,s);sendOrEdit_(chatId,editSummary_(s.editing_tx||{}),editMenu_());return;}
    if(step==='WAIT_TEXT_EDIT_KET'){if(s.editing_tx)s.editing_tx.keterangan=userText;s.step=null;saveSession_(chatId,s);sendOrEdit_(chatId,editSummary_(s.editing_tx||{}),editMenu_());return;}
    if(step==='WAIT_TEXT_EDIT_CAT'){if(s.editing_tx)s.editing_tx.kategoriPilihan=userText;s.step=null;saveSession_(chatId,s);sendOrEdit_(chatId,editSummary_(s.editing_tx||{}),editMenu_());return;}
    s.step='MENU';saveSession_(chatId,s);executeNaturalSearch_(chatId,userText,1);
  }catch(e){console.error('[LAVI TG text] '+e.stack);resetSession_(chatId,true);sendOrEdit_(chatId,menuText_(),mainMenu_());}finally{deleteMessage_(chatId,messageId);}}

  function handleCallback_(chatId,cbId,data,msgId){if(!isAllowed_(chatId)){answerCb_(cbId,'❌ Akses tidak diizinkan.',true);return;}const ownAck=(data==='do_save_transaction'||data==='confirm_sensitive_save'||data==='undo_last_tx'||data==='confirm_undo_last_tx'||data==='do_save_edited_tx'||data==='confirm_save_edited_tx'||data.indexOf('tx_del_confirm:')===0);if(!ownAck)answerCb_(cbId,'',false);if(data==='noop')return;let s=getSession_(chatId);if(msgId)s.last_msg_id=msgId;try{
    if(data==='btn_menu'){s=resetSession_(chatId,true);sendOrEdit_(chatId,menuText_(),mainMenu_());return;}
    if(data==='btn_help'){const mp=getMappedPerson_(chatId);sendOrEdit_(chatId,'<b>❓ BANTUAN & PANDUAN BOT</b>\n━━━━━━━━━━━━━━━━━━━━\n<b>📋 Fitur Utama:</b>\n• ➕ Catat Pemasukan, Pengeluaran, Transfer & Investasi\n• 💰 Cek Saldo per Person atau Global\n• 🔍 Filter & Cari (Tanggal / Person / Jenis / Kata Kunci)\n• ✏️ Edit & 🗑️ Hapus Transaksi dengan konfirmasi\n• 🔁 Ulangi / ↩️ batalkan transaksi terakhir (maks. 1 menit)\n• 📊 Dashboard bulanan & perbandingan bulan lalu\n• 🧠 Pencarian natural (contoh: pengeluaran Abi bulan ini makanan)\n• 📄 Export Excel / PDF\n• 🩺 Status sistem\n\n<b>⚡ Perintah Cepat:</b>\n• /start atau /menu — Menu Utama\n• /total — Cek saldo cepat\n\n<b>📌 Person Default Anda:</b> '+(mp?'<b>'+esc_(mp)+'</b>':'<i>Belum diset</i>'),[[btn_('📌 Set Person Default','prompt_set_default_person')],[btn_('◀️ Menu Utama','btn_menu')]]);return;}
    if(data==='prompt_set_default_person'){sendOrEdit_(chatId,'<b>📌 SET PERSON DEFAULT</b>\n━━━━━━━━━━━━━━━━━━━━\nPilih nama Person yang mewakili Chat ID Telegram Anda.',userMapMenu_());return;}
    if(data.indexOf('set_user_map:')===0){const p=data.split(':').slice(1).join(':');if(p==='clear'){setMappedPerson_(chatId,null);sendOrEdit_(chatId,'🗑️ <b>Mapping Person Default Dihapus.</b>',[[btn_('◀️ Menu Utama','btn_menu')]]);}else{setMappedPerson_(chatId,p);sendOrEdit_(chatId,'✅ <b>Person Default Disimpan!</b>\nChat Anda → <b>'+esc_(p)+'</b>',[[btn_('◀️ Menu Utama','btn_menu')]]);}return;}
    if(data==='btn_cek_saldo'){sendOrEdit_(chatId,'<b>💰 CEK SALDO & TABUNGAN</b>\n━━━━━━━━━━━━━━━━━━━━\nPilih <b>Person</b> atau <b>Semua Person</b>:',saldoPersonMenu_());return;}
    if(data.indexOf('saldo_select:')===0){showBalance_(chatId,data.substring(13));return;}
    if(data==='btn_today_summary'){executeFilter_(chatId,'date_today','',1);return;}
    if(data==='btn_recent_10'){showRecent_(chatId);return;}
    if(data==='btn_dashboard_month'){showMonthlyDashboard_(chatId);return;}
    if(data==='btn_system_status'){showSystemStatus_(chatId);return;}
    if(data==='btn_export'){sendOrEdit_(chatId,'<b>📄 EXPORT TRANSAKSI</b>\n━━━━━━━━━━━━━━━━━━━━\nPilih cakupan data yang akan diekspor:',exportScopeMenu_());return;}
    if(data==='filter_prompt_natural'){s.step='WAIT_NATURAL_SEARCH';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>🧠 PENCARIAN NATURAL</b>\n━━━━━━━━━━━━━━━━━━━━\nKetik seperti Anda bicara biasa.\nContoh: <code>pengeluaran Abi bulan ini makanan</code>',[[btn_('◀️ Batal','btn_filter_menu')]]);return;}
    if(data.indexOf('export_scope:')===0){const type=data.substring(13),labels={today:'Hari Ini',month:'Bulan Ini',prevmonth:'Bulan Lalu',all:'Semua Data'};showExportFormat_(chatId,{type:type},labels[type]||type);return;}
    if(data==='export_scope_person'){const rows=[];let r=[];DEFAULT_PERSONS.forEach(p=>{r.push(btn_('👤 '+p,'export_person:'+p));if(r.length===2){rows.push(r);r=[];}});if(r.length)rows.push(r);rows.push([btn_('◀️ Kembali','btn_export')]);sendOrEdit_(chatId,'<b>👤 EXPORT PER PERSON</b>\nPilih Person:',rows);return;}
    if(data.indexOf('export_person:')===0){const p=data.substring(14);showExportFormat_(chatId,{type:'person',person:p},'Person '+p);return;}
    if(data==='export_scope_range'){s.step='WAIT_EXPORT_DATERANGE';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📆 EXPORT RENTANG TANGGAL</b>\n━━━━━━━━━━━━━━━━━━━━\nKetik: <code>dd/mm/yyyy - dd/mm/yyyy</code>',[[btn_('◀️ Batal','btn_export')]]);return;}
    if(data.indexOf('export_do:')===0){sendExport_(chatId,data.substring(10));return;}
    if(data==='btn_filter_menu'){sendOrEdit_(chatId,'<b>🔍 FILTER & CARI TRANSAKSI</b>\n━━━━━━━━━━━━━━━━━━━━\n📅 <b>Tanggal</b> : Hari Ini, Kemarin, Minggu, Bulan\n👤 <b>Person</b> : Abi, Ummah, Dafiq, Laviska, Toko\n🏷️ <b>Jenis</b> : Pemasukan / Pengeluaran / Investasi\n💳 <b>Dompet</b> : Cash, Dana, Gopay, dll.\n🔤 <b>Kata Kunci</b>: Cari teks bebas',filterMenu_());return;}
    if(data==='filter_menu_date'){sendOrEdit_(chatId,'<b>📅 PILIH FILTER TANGGAL</b>\n━━━━━━━━━━━━━━━━━━━━',[[btn_('📅 Hari Ini','filter_run:date_today'),btn_('📅 Kemarin','filter_run:date_yesterday')],[btn_('📆 Minggu Ini','filter_run:date_week'),btn_('🗓️ Bulan Ini','filter_run:date_month')],[btn_('🗓️ Bulan Lalu','filter_run:date_prevmonth'),btn_('✏️ Custom Tanggal','filter_prompt_date')],[btn_('📆 Rentang Tanggal','filter_prompt_daterange')],[btn_('◀️ Kembali','btn_filter_menu')]]);return;}
    if(data==='filter_prompt_daterange'){s.step='WAIT_FILTER_DATERANGE';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📆 FILTER RENTANG TANGGAL</b>\n━━━━━━━━━━━━━━━━━━━━\nKetik rentang tanggal:\n<code>dd/mm/yyyy - dd/mm/yyyy</code>',[[btn_('◀️ Batal','btn_filter_menu')]]);return;}
    if(data.indexOf('filter_page:')===0){const st=s.filter_state||{},pg=Number(data.substring(12))||1;if(st.type==='natural')executeNaturalSearch_(chatId,st.val||'',pg);else executeFilter_(chatId,st.type||'all',st.val||'',pg);return;}
    if(data==='filter_menu_person'){const rows=[];let r=[];DEFAULT_PERSONS.forEach(p=>{r.push(btn_('👤 '+p,'filter_run:person_'+p));if(r.length===2){rows.push(r);r=[];}});if(r.length)rows.push(r);rows.push([btn_('👥 Semua Person','filter_run:all_50')],[btn_('◀️ Kembali','btn_filter_menu')]);sendOrEdit_(chatId,'<b>👤 PILIH FILTER PERSON</b>\n━━━━━━━━━━━━━━━━━━━━',rows);return;}
    if(data==='filter_menu_jenis'){sendOrEdit_(chatId,'<b>🏷️ PILIH FILTER JENIS</b>\n━━━━━━━━━━━━━━━━━━━━',[[btn_('🔴 Pengeluaran','filter_run:jenis_Pengeluaran'),btn_('🟢 Pemasukan','filter_run:jenis_Pemasukan')],[btn_('📈 Investasi & Tabungan','filter_run:jenis_Investasi'),btn_('🔄 Pemindahan Saldo','filter_run:jenis_Pemindahan')],[btn_('◀️ Kembali','btn_filter_menu')]]);return;}
    if(data==='filter_menu_wallet'){const rows=[];let r=[];wallets_().forEach(w=>{r.push(btn_((w==='Cash'?'💵 ':w.indexOf('Kartu')>=0?'💳 ':'🏦 ')+w,'filter_run:wallet_'+w));if(r.length===2){rows.push(r);r=[];}});if(r.length)rows.push(r);rows.push([btn_('◀️ Kembali','btn_filter_menu')]);sendOrEdit_(chatId,'<b>💳 PILIH FILTER DOMPET</b>\n━━━━━━━━━━━━━━━━━━━━',rows);return;}
    if(data==='filter_prompt_keyword'||data==='btn_search_prompt'){s.step='WAIT_SEARCH_KEYWORD';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>🔤 CARI KATA KUNCI</b>\n━━━━━━━━━━━━━━━━━━━━\nKetik kata kunci transaksi:',[[btn_('◀️ Batal','btn_filter_menu')]]);return;}
    if(data==='filter_prompt_date'){s.step='WAIT_FILTER_DATE';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📅 FILTER TANGGAL CUSTOM</b>\n━━━━━━━━━━━━━━━━━━━━\nKetik tanggal: <code>dd/mm/yyyy</code>',[[btn_('◀️ Batal','btn_filter_menu')]]);return;}
    if(data.indexOf('filter_run:')===0){const k=data.substring(11);if(k.indexOf('date_')===0)executeFilter_(chatId,k,'',1);else if(k.indexOf('person_')===0)executeFilter_(chatId,'person',k.substring(7),1);else if(k.indexOf('jenis_')===0)executeFilter_(chatId,'jenis',k.substring(6),1);else if(k.indexOf('wallet_')===0)executeFilter_(chatId,'wallet',k.substring(7),1);else executeFilter_(chatId,'all','',1);return;}
    if(data.indexOf('tx_view:')===0){const id=data.substring(8),t=findTxById_(chatId,id);if(!t){answerCb_(cbId,'Transaksi tidak ditemukan.',true);return;}s.selected_tx_id=id;saveSession_(chatId,s);const extra=t.jenis==='Pemindahan Saldo'?'🔄 <b>Dari:</b> '+esc_(t.sumberDana)+' ➡️ <b>Ke:</b> '+esc_(t.tujuanDana)+'\n👥 <b>Person Tujuan:</b> '+esc_(t.sumberLayanan||'-')+'\n':'💳 <b>Dompet:</b> '+esc_(t.jenisSaldo)+'\n';sendOrEdit_(chatId,'<b>📜 DETAIL TRANSAKSI</b>\n━━━━━━━━━━━━━━━━━━━━\n🆔 <b>ID:</b> <code>'+esc_(t.id)+'</code>\n📅 <b>Tanggal:</b> '+esc_(t.tanggal)+'\n👤 <b>Person:</b> '+esc_(t.kategoriPerson)+'\n🏷️ <b>Jenis:</b> '+esc_(t.jenis)+'\n📁 <b>Kategori:</b> '+esc_(t.kategoriPilihan)+'\n'+extra+'💰 <b>Nominal:</b> '+rupiah_(t.nominal)+'\n✏️ <b>Ket.:</b> '+esc_(t.keterangan)+'\n━━━━━━━━━━━━━━━━━━━━',[[btn_('✏️ Edit','tx_edit_start:'+t.id),btn_('🗑️ Hapus','tx_del_confirm:'+t.id)],[urlBtn_('🌐 Buka di Aplikasi','https://finance.lavi.web.id/data?tx='+encodeURIComponent(t.id))],[btn_('◀️ Kembali ke Daftar','btn_recent_10'),btn_('🏠 Menu','btn_menu')]]);return;}
    if(data.indexOf('tx_del_confirm:')===0){answerCb_(cbId,'🛡️ Konfirmasi penghapusan transaksi. Tindakan ini tidak dapat dibatalkan.',true);const t=findTxById_(chatId,data.substring(15));if(!t)return;s.deleting_tx=t;saveSession_(chatId,s);sendOrEdit_(chatId,'<b>⚠️ KONFIRMASI HAPUS TRANSAKSI</b>\n━━━━━━━━━━━━━━━━━━━━\n• 🆔 <code>'+esc_(t.id)+'</code>\n• 📅 '+esc_(t.tanggal)+'\n• 👤 '+esc_(t.kategoriPerson)+'\n• 💰 '+rupiah_(t.nominal)+'\n• 📁 '+esc_(t.kategoriPilihan)+'\n• ✏️ '+esc_(t.keterangan)+'\n\n<b>⚠️ Tindakan ini tidak dapat dibatalkan!</b>',[[btn_('🗑️ YA, HAPUS SEKARANG','do_delete_tx')],[btn_('❌ BATAL','tx_view:'+t.id)]]);return;}
    if(data==='do_delete_tx'){const t=s.deleting_tx;if(!t)return;progress_(chatId,'🗑️ MENGHAPUS TRANSAKSI',['Menghapus data...','Memperbarui saldo...']);let res;try{res=retryInternal_(function(){return deleteTransaction(t.id);},1);}catch(e){res={success:false,message:String(e)};}clearTxCache_(chatId);sendOrEdit_(chatId,res&&res.success?'<b>✅ TRANSAKSI BERHASIL DIHAPUS</b>\n━━━━━━━━━━━━━━━━━━━━\n📁 '+esc_(t.kategoriPilihan)+' | '+rupiah_(t.nominal)+' | '+esc_(t.tanggal):'❌ <b>Gagal Hapus Transaksi!</b>\nAlasan: '+esc_(res&&res.message||'Gagal'),[[btn_('📜 Kembali ke Daftar','btn_recent_10')],[btn_('◀️ Menu Utama','btn_menu')]]);return;}
    if(data.indexOf('tx_edit_start:')===0){const t=findTxById_(chatId,data.substring(14));if(!t)return;s.editing_tx=JSON.parse(JSON.stringify(t));saveSession_(chatId,s);sendOrEdit_(chatId,editSummary_(s.editing_tx),editMenu_());return;}
    if(data==='edit_back_to_summary'){sendOrEdit_(chatId,editSummary_(s.editing_tx||{}),editMenu_());return;}
    if(data==='edit_sel_person'){const rows=[];let r=[];DEFAULT_PERSONS.forEach(p=>{r.push(btn_(p,'save_edit_field:kategoriPerson:'+p));if(r.length===2){rows.push(r);r=[];}});if(r.length)rows.push(r);rows.push([btn_('◀️ Batal Edit','edit_back_to_summary')]);sendOrEdit_(chatId,'👤 <b>Pilih Person Baru:</b>',rows);return;}
    if(data==='edit_sel_jenis'){sendOrEdit_(chatId,'🏷️ <b>Pilih Jenis Transaksi Baru:</b>',['Pengeluaran','Pemasukan','Pemindahan Saldo','Investasi dan Tabungan'].map(j=>[btn_(j,'save_edit_field:jenis:'+j)]).concat([[btn_('◀️ Batal Edit','edit_back_to_summary')]]));return;}
    if(data==='edit_sel_kategori'){s.edit_cat_page=s.edit_cat_page||1;saveSession_(chatId,s);sendOrEdit_(chatId,'📁 <b>Pilih Kategori Baru ('+esc_((s.editing_tx||{}).jenis||'Pengeluaran')+'):</b>',categoryMenu_((s.editing_tx||{}).jenis||'Pengeluaran',s.edit_cat_page,true));return;}
    if(data.indexOf('edit_cat_page:')===0){s.edit_cat_page=Number(data.substring(14))||1;saveSession_(chatId,s);sendOrEdit_(chatId,'📁 <b>Pilih Kategori Baru:</b>',categoryMenu_((s.editing_tx||{}).jenis||'Pengeluaran',s.edit_cat_page,true));return;}
    if(data==='edit_sel_saldo'){const rows=[];let r=[];wallets_().forEach(w=>{r.push(btn_(w,'save_edit_field:jenisSaldo:'+w));if(r.length===2){rows.push(r);r=[];}});if(r.length)rows.push(r);rows.push([btn_('◀️ Batal Edit','edit_back_to_summary')]);sendOrEdit_(chatId,'💳 <b>Pilih Dompet / Saldo Baru:</b>',rows);return;}
    if(data==='edit_sel_nominal'){s.step='WAIT_TEXT_EDIT_NOMINAL';saveSession_(chatId,s);sendOrEdit_(chatId,'💰 <b>Ketik Nominal Baru:</b>\n<i>Saat ini: '+rupiah_((s.editing_tx||{}).nominal||0)+'</i>',[[btn_('◀️ Batal Edit','edit_back_to_summary')]]);return;}
    if(data==='edit_sel_ket'){s.step='WAIT_TEXT_EDIT_KET';saveSession_(chatId,s);sendOrEdit_(chatId,'✏️ <b>Ketik Keterangan Baru:</b>',[[btn_('◀️ Batal Edit','edit_back_to_summary')]]);return;}
    if(data==='prompt_edit_custom_cat'){s.step='WAIT_TEXT_EDIT_CAT';saveSession_(chatId,s);sendOrEdit_(chatId,'✏️ <b>Ketik Nama Kategori Baru:</b>',[[btn_('◀️ Batal Edit','edit_back_to_summary')]]);return;}
    if(data.indexOf('save_edit_field:')===0){const parts=data.split(':'),field=parts[1],value=parts.slice(2).join(':');if(s.editing_tx)s.editing_tx[field]=value;s.edit_cat_page=1;saveSession_(chatId,s);sendOrEdit_(chatId,editSummary_(s.editing_tx||{}),editMenu_());return;}
    if(data==='do_save_edited_tx'){
      const t=s.editing_tx;if(!t){answerCb_(cbId,'Data edit tidak tersedia.',true);return;}
      answerCb_(cbId,'🛡️ Periksa kembali perubahan sebelum disimpan.',true);
      sendOrEdit_(chatId,'<b>🛡️ KONFIRMASI SIMPAN PERUBAHAN</b>\n━━━━━━━━━━━━━━━━━━━━\n'+editSummary_(t).replace(/^<b>.*?<\/b>\n━━━━━━━━━━━━━━━━━━━━\n/,'')+'\n\n<b>Simpan perubahan ini?</b>',[[btn_('✅ Ya, Simpan Perubahan','confirm_save_edited_tx')],[btn_('❌ Batal','edit_back_to_summary')]]);return;
    }
    if(data==='confirm_save_edited_tx'){answerCb_(cbId,'Menyimpan perubahan...',false);saveEditedTx_(chatId);return;}
    if(data==='btn_stats'){progress_(chatId,'📈 MEMUAT STATISTIK',['Mengambil ringkasan statistik...','Menghitung saldo bersih...']);let res=null;const sc=CacheService.getScriptCache();try{const sr=sc.get('lftg_stats_v1');if(sr)res=JSON.parse(sr);}catch(_){}if(!res){res=getExportSummary();try{sc.put('lftg_stats_v1',JSON.stringify(res),60);}catch(_){}}if(res&&res.totalTransactions!=null){const lines=['<b>📈 STATISTIK KEUANGAN AKUMULATIF</b>','━━━━━━━━━━━━━━━━━━━━','📊 Total Transaksi    : <b>'+Number(res.totalTransactions).toLocaleString('id-ID')+'</b>','🟢 Total Pemasukan    : <b>'+rupiah_(res.totalPemasukan)+'</b>','🔴 Total Pengeluaran  : <b>'+rupiah_(res.totalPengeluaran)+'</b>',(Number(res.saldoBersih)>=0?'🟢':'🔴')+' Saldo Bersih       : <b>'+rupiah_(res.saldoBersih)+'</b>','━━━━━━━━━━━━━━━━━━━━','<b>👤 Saldo Bersih per Person:</b>'];Object.keys(res.byPerson||{}).forEach(p=>{const d=res.byPerson[p],v=typeof d==='object'?Number(d.saldo)||0:Number(d)||0,c=typeof d==='object'?Number(d.count)||0:0;lines.push('  '+(v>=0?'🟢':'🔴')+' <b>'+esc_(p)+'</b> ('+c+' tx): '+rupiah_(v));});const cats=(res.categories&&res.categories.pengeluaran)||res.topKategoriPengeluaran||res.topCategories||[];if(cats.length){lines.push('━━━━━━━━━━━━━━━━━━━━','<b>📊 TOP 5 KATEGORI PENGELUARAN:</b>');cats.slice(0,5).forEach((x,i)=>lines.push('  '+(i+1)+'. <b>'+esc_(x.name||x.kategori||'?')+'</b>: '+rupiah_(x.total||x.nilai||0)));}sendOrEdit_(chatId,lines.join('\n'),[[btn_('📅 Filter Bulan Ini','filter_run:date_month'),btn_('💰 Cek Saldo','btn_cek_saldo')],[btn_('◀️ Menu Utama','btn_menu')]]);}else sendOrEdit_(chatId,'❌ <b>Gagal memuat data statistik.</b>',[[btn_('◀️ Menu Utama','btn_menu')]]);return;}
    if(['wizard_start','set_person_back','wizard_start_manual'].indexOf(data)>=0){s.tanggal=fmtDate_();const mp=getMappedPerson_(chatId);if(mp&&data!=='wizard_start_manual'){s.person=mp;s.step='SELECT_TYPE';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📝 TRANSAKSI BARU</b>\n━━━━━━━━━━━━━━━━━━━━\n📅 Tanggal : <b>'+s.tanggal+'</b>\n👤 Person  : <b>'+esc_(mp)+'</b> <i>(Default)</i>\n\nPilih <b>Jenis Transaksi</b>:',typeMenu_(true));}else{s.step='SELECT_PERSON';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📝 TRANSAKSI BARU (1/6)</b>\n━━━━━━━━━━━━━━━━━━━━\n📅 Tanggal: <b>'+s.tanggal+'</b>\n\nPilih <b>Person / Sub-Akun</b>:',personMenu_());}return;}
    if(data.indexOf('set_person:')===0||data==='set_type_back'){if(data.indexOf('set_person:')===0)s.person=data.substring(11);s.step='SELECT_TYPE';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📝 TRANSAKSI BARU (2/6)</b>\n━━━━━━━━━━━━━━━━━━━━\n👤 Person : <b>'+esc_(s.person)+'</b>\n\nPilih <b>Jenis Transaksi</b>:',typeMenu_(!!getMappedPerson_(chatId)));return;}
    if(data==='set_type:Pemindahan Saldo'){s.jenis='Pemindahan Saldo';s.kategori='Pemindahan Saldo';s.step='SELECT_SALDO_ASAL';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>🔄 PEMINDAHAN SALDO (1/4)</b>\n━━━━━━━━━━━━━━━━━━━━\n👤 Person Asal : <b>'+esc_(s.person)+'</b>\n\nPilih <b>Dompet ASAL</b>:',walletMenu_('asal'));return;}
    if(data.indexOf('set_saldo_asal:')===0||data==='set_saldo_asal_back'){if(data.indexOf('set_saldo_asal:')===0){s.saldo_asal=data.substring(16);s.saldo=s.saldo_asal;}s.step='SELECT_SALDO_TUJUAN';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>🔄 PEMINDAHAN SALDO (2/4)</b>\n━━━━━━━━━━━━━━━━━━━━\n👤 Person Asal : <b>'+esc_(s.person)+'</b>\n💳 Dari Dompet : <b>'+esc_(s.saldo_asal)+'</b>\n\nPilih <b>Dompet TUJUAN</b>:',walletMenu_('tujuan'));return;}
    if(data.indexOf('set_saldo_tujuan:')===0||data==='set_saldo_tujuan_back'){if(data.indexOf('set_saldo_tujuan:')===0)s.saldo_tujuan=data.substring(18);s.step='SELECT_PERSON_TUJUAN';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>🔄 PEMINDAHAN SALDO (3/4)</b>\n━━━━━━━━━━━━━━━━━━━━\n👤 Person Asal : <b>'+esc_(s.person)+'</b>\n💳 Dari : <b>'+esc_(s.saldo_asal)+'</b> ➡️ <b>'+esc_(s.saldo_tujuan)+'</b>\n\nPilih <b>Person TUJUAN</b>:',targetPersonMenu_(s.person||'Abi'));return;}
    if(data.indexOf('set_person_tujuan:')===0){s.person_tujuan=data.substring(19);s.step='SELECT_NOMINAL';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>🔄 PEMINDAHAN SALDO (4/4)</b>\n━━━━━━━━━━━━━━━━━━━━\n👤 Asal   : <b>'+esc_(s.person)+'</b> ('+esc_(s.saldo_asal)+')\n👥 Tujuan : <b>'+esc_(s.person_tujuan)+'</b> ('+esc_(s.saldo_tujuan)+')\n\nPilih atau ketik <b>Nominal Transfer</b>:',nominalMenu_());return;}
    if(data.indexOf('set_type:')===0||data==='set_cat_back'||data.indexOf('cat_page:')===0){if(data.indexOf('set_type:')===0){s.jenis=data.substring(9);s.cat_page=1;}if(data.indexOf('cat_page:')===0)s.cat_page=Number(data.substring(9))||1;s.step='SELECT_CATEGORY';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📝 TRANSAKSI BARU (3/6)</b>\n━━━━━━━━━━━━━━━━━━━━\n👤 Person : <b>'+esc_(s.person)+'</b>\n🏷️ Jenis  : <b>'+esc_(s.jenis)+'</b>\n\nPilih <b>Kategori</b>:',categoryMenu_(s.jenis||'Pengeluaran',s.cat_page||1,false));return;}
    if(data.indexOf('set_cat:')===0||data==='set_saldo_back'){if(data.indexOf('set_cat:')===0)s.kategori=data.substring(8);s.step='SELECT_SALDO';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📝 TRANSAKSI BARU (4/6)</b>\n━━━━━━━━━━━━━━━━━━━━\n👤 Person   : <b>'+esc_(s.person)+'</b>\n🏷️ Jenis    : <b>'+esc_(s.jenis)+'</b>\n📁 Kategori : <b>'+esc_(s.kategori)+'</b>\n\nPilih <b>Dompet / Saldo</b>:',walletMenu_());return;}
    if(data.indexOf('set_saldo:')===0||data==='back_quick_nom'||data==='change_nom'){if(data.indexOf('set_saldo:')===0)s.saldo=data.substring(10);s.step='SELECT_NOMINAL';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📝 TRANSAKSI BARU (5/6)</b>\n━━━━━━━━━━━━━━━━━━━━\n👤 Person   : <b>'+esc_(s.person)+'</b>\n🏷️ Jenis    : <b>'+esc_(s.jenis)+'</b>\n📁 Kategori : <b>'+esc_(s.kategori)+'</b>\n💳 Dompet   : <b>'+esc_(s.saldo)+'</b>\n\nPilih atau ketik <b>Nominal Rp</b>:',nominalMenu_());return;}
    if(data==='open_keypad'){s.keypad_val='';s.step='KEYPAD_NOMINAL';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>🧮 KEYPAD NOMINAL</b>\n━━━━━━━━━━━━━━━━━━━━\nNominal : <b>Rp 0</b>\n\nSentuh tombol angka:',keypadMenu_());return;}
    if(data.indexOf('pad_add:')===0){let cur=String(s.keypad_val||'');if(cur.length<12)cur=(cur+data.substring(8)).replace(/^0+/,'');s.keypad_val=cur;saveSession_(chatId,s);sendOrEdit_(chatId,'<b>🧮 KEYPAD NOMINAL</b>\n━━━━━━━━━━━━━━━━━━━━\nNominal : <b>'+(cur?rupiah_(Number(cur)):'Rp 0')+'</b>\n\nSentuh tombol angka:',keypadMenu_());return;}
    if(data==='pad_backspace'){s.keypad_val=String(s.keypad_val||'').slice(0,-1);saveSession_(chatId,s);sendOrEdit_(chatId,'<b>🧮 KEYPAD NOMINAL</b>\n━━━━━━━━━━━━━━━━━━━━\nNominal : <b>'+(s.keypad_val?rupiah_(Number(s.keypad_val)):'Rp 0')+'</b>',keypadMenu_());return;}
    if(data==='pad_clear'){s.keypad_val='';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>🧮 KEYPAD NOMINAL</b>\n━━━━━━━━━━━━━━━━━━━━\nNominal : <b>Rp 0</b>',keypadMenu_());return;}
    if(data==='pad_submit'){const n=Number(s.keypad_val||0);if(!(n>0)){answerCb_(cbId,'⚠️ Masukkan nominal lebih dari Rp 0!',true);return;}s.nominal=n;s.step='WAIT_TEXT_KETERANGAN';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📝 TRANSAKSI BARU (6/6)</b>\n━━━━━━━━━━━━━━━━━━━━\n💰 Nominal  : <b>'+rupiah_(n)+'</b>\n\n✏️ <b>Ketik Keterangan Transaksi:</b>',keteranganMenu_());return;}
    if(data.indexOf('set_nom:')===0){s.nominal=Number(data.substring(8));s.step='WAIT_TEXT_KETERANGAN';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>📝 TRANSAKSI BARU (6/6)</b>\n━━━━━━━━━━━━━━━━━━━━\n💰 Nominal  : <b>'+rupiah_(s.nominal)+'</b>\n\n✏️ <b>Ketik Keterangan Transaksi:</b>',keteranganMenu_());return;}
    if(data.indexOf('set_ket:')===0||data==='change_ket'){if(data.indexOf('set_ket:')===0)s.keterangan=data.substring(8);s.step='CONFIRMATION';saveSession_(chatId,s);sendOrEdit_(chatId,confirmationText_(s),confirmMenu_());return;}
    if(data==='prompt_custom_person'){s.step='WAIT_TEXT_PERSON';saveSession_(chatId,s);sendOrEdit_(chatId,'✏️ <b>Ketik Nama Person / Sub-Akun:</b>',[[btn_('◀️ Batal','wizard_start')]]);return;}
    if(data==='prompt_custom_cat'){s.step='WAIT_TEXT_CATEGORY';saveSession_(chatId,s);sendOrEdit_(chatId,'✏️ <b>Ketik Nama Kategori Custom:</b>',[[btn_('◀️ Batal','set_type_back')]]);return;}
    if(data==='prompt_custom_nom'){s.step='WAIT_TEXT_NOMINAL';saveSession_(chatId,s);sendOrEdit_(chatId,'✏️ <b>Ketik Nominal (contoh: 25000 atau 1500000):</b>',[[btn_('◀️ Batal','back_quick_nom')]]);return;}
    if(data==='prompt_custom_ket'){s.step='WAIT_TEXT_KETERANGAN';saveSession_(chatId,s);sendOrEdit_(chatId,'✏️ <b>Ketik Keterangan Transaksi:</b>',[[btn_('◀️ Batal','back_quick_nom')]]);return;}
    if(data==='do_save_transaction'){
      const risk=expenseRisk_(s),sensitive=(s.jenis==='Pemindahan Saldo'||risk.large||risk.low);
      if(sensitive){answerCb_(cbId,'🛡️ Transaksi ini membutuhkan konfirmasi tambahan.',true);sendOrEdit_(chatId,sensitiveSaveText_(s,risk),[[btn_('✅ Ya, Tetap Simpan','confirm_sensitive_save')],[btn_('❌ Batal / Periksa Lagi','btn_menu')]]);return;}
      answerCb_(cbId,'Menyimpan transaksi...',false);saveWizardTx_(chatId);return;
    }
    if(data==='confirm_sensitive_save'){answerCb_(cbId,'Menyimpan transaksi...',false);saveWizardTx_(chatId);return;}
    if(data==='undo_last_tx'){
      const u=undoInfo_(s);if(!u.valid){answerCb_(cbId,'⏱️ Batas waktu 1 menit sudah berakhir.',true);delete s.last_transaction_id;delete s.last_transaction_at;saveSession_(chatId,s);return;}
      answerCb_(cbId,'🛡️ Batalkan transaksi terakhir? Tindakan ini akan menghapus transaksi.',true);
      const t=findTxById_(chatId,u.id);sendOrEdit_(chatId,'<b>↩️ KONFIRMASI BATAL TRANSAKSI</b>\n━━━━━━━━━━━━━━━━━━━━\n🆔 <code>'+esc_(u.id)+'</code>\n'+(t?'📅 '+esc_(t.tanggal)+'\n👤 '+esc_(t.kategoriPerson)+'\n💰 '+rupiah_(t.nominal)+'\n📁 '+esc_(t.kategoriPilihan)+'\n':'')+'⏱️ Sisa waktu: <b>'+Math.ceil(u.remaining/1000)+' detik</b>\n\n<b>Yakin membatalkan transaksi?</b>',[[btn_('✅ Ya, Batalkan Transaksi','confirm_undo_last_tx')],[btn_('❌ Tidak','btn_menu')]]);return;
    }
    if(data==='confirm_undo_last_tx'){answerCb_(cbId,'Membatalkan transaksi...',false);performUndo_(chatId);return;}
    if(data==='wizard_repeat_last'){const last=s.last_payload;if(!last){answerCb_(cbId,'Tidak ada transaksi sebelumnya untuk diulangi.',true);return;}s.tanggal=fmtDate_();s.person=last.kategoriPerson||'Abi';s.jenis=last.jenis||last.jenisTransaksi||'Pengeluaran';s.kategori=last.kategoriPilihan||last.kategoriPengeluaran||last.kategoriPemasukan||last.jenisTabungan||'-';s.saldo=last.jenisSaldo||last.sumberDana||'Cash';s.nominal=Number(last.nominal)||0;s.keterangan=last.keterangan||'-';if(s.jenis==='Pemindahan Saldo'){s.saldo_asal=last.sumberDana||last.jenisSaldo;s.saldo_tujuan=last.tujuanDana;s.person_tujuan=last.sumberLayanan||s.person;}s.step='CONFIRMATION';saveSession_(chatId,s);sendOrEdit_(chatId,'<b>🔁 ULANGI TRANSAKSI TERAKHIR</b>\n━━━━━━━━━━━━━━━━━━━━\n'+confirmationText_(s).replace(/^<b>.*?<\/b>\n━━━━━━━━━━━━━━━━━━━━\n/,'') ,confirmMenu_());return;}
    sendOrEdit_(chatId,menuText_(),mainMenu_());
  }catch(e){console.error('[LAVI TG callback '+data+'] '+(e.stack||e));sendOrEdit_(chatId,'❌ <b>Terjadi Kesalahan Sistem!</b>\n<code>'+esc_(String(e.message||e).slice(0,180))+'</code>',[[btn_('◀️ Menu Utama','btn_menu')]]);}}

  function isDuplicateUpdate_(updateId){
    if(updateId==null) return false;
    const key='lftg_upd_'+String(updateId), cache=CacheService.getScriptCache();
    const lock=LockService.getScriptLock();
    try{
      lock.tryLock(1500);
      if(cache.get(key)) return true;
      cache.put(key,'1',21600);
      return false;
    }catch(_){
      try{if(cache.get(key))return true;cache.put(key,'1',21600);}catch(__){}
      return false;
    }finally{try{lock.releaseLock();}catch(_){}}
  }

  function handleUpdate_(e,update){
    const key = e && e.parameter ? String(e.parameter.key || '') : '';
    if (!webhookKey_() || key !== webhookKey_()) return json_({ok:false,error:'invalid_webhook_key'});
    update = update || {};
    if (isDuplicateUpdate_(update.update_id)) return json_({ok:true,duplicate:true});
    try {
      if(update.callback_query){const q=update.callback_query,chat=q.message&&q.message.chat&&q.message.chat.id;if(!chat)return json_({ok:true,ignored:true});handleCallback_(chat,q.id,String(q.data||''),q.message&&q.message.message_id);return json_({ok:true});}
      const m=update.message||update.edited_message;if(!m||!m.chat)return json_({ok:true,ignored:true});const chatId=m.chat.id;if(!isAllowed_(chatId))return json_({ok:true,unauthorized:true});const text=String(m.text||'').trim();if(!text)return json_({ok:true,ignored:true});if(text.charAt(0)==='/')handleCommand_(chatId,m.message_id,text);else handleText_(chatId,m.message_id,text);return json_({ok:true});
    } catch(err){console.error('[LAVI TG webhook] '+(err.stack||err));return json_({ok:false,error:String(err.message||err)});}
  }
  function json_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);}
  function relaySecret_(){
    const bridge=String(getLaviBridgeSecret_()||'').trim();
    if(!bridge) throw new Error('LAVI_BRIDGE_SECRET belum dikonfigurasi.');
    const bytes=Utilities.computeHmacSha256Signature('lavi-finance-telegram-relay-v1',bridge,Utilities.Charset.UTF_8);
    return Utilities.base64EncodeWebSafe(bytes).replace(/=+$/g,'');
  }
  function relaySecretHash_(){
    const bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,relaySecret_(),Utilities.Charset.UTF_8);
    return Utilities.base64EncodeWebSafe(bytes).replace(/=+$/g,'');
  }
  function constantEq_(a,b){
    a=String(a||'');b=String(b||'');let diff=a.length^b.length;const n=Math.max(a.length,b.length);
    for(let i=0;i<n;i++) diff|=(a.charCodeAt(i%Math.max(1,a.length))||0)^(b.charCodeAt(i%Math.max(1,b.length))||0);
    return diff===0;
  }
  function relayGet_(e){
    const p=e&&e.parameter?e.parameter:{};
    const enc=String(p.u||''),sig=String(p.sig||'');
    if(!enc||enc.length>12000||!sig) return json_({ok:false,error:'invalid_relay_payload'});
    try{
      const bytes=Utilities.base64DecodeWebSafe(enc);
      const text=Utilities.newBlob(bytes).getDataAsString('UTF-8');
      const expected=Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(text,relaySecret_(),Utilities.Charset.UTF_8)).replace(/=+$/g,'');
      if(!constantEq_(sig,expected)) return json_({ok:false,error:'invalid_relay_signature'});
      const update=JSON.parse(text);
      return handleUpdate_({parameter:{key:webhookKey_()}},update);
    }catch(err){
      console.error('[LAVI TG relay] '+(err.stack||err));
      return json_({ok:false,error:'relay_decode_failed'});
    }
  }
  function setup_(){
    const token=token_(),ids=allowedIds_(); if(!token)throw new Error('LAVI_FINANCE_TELEGRAM_TOKEN belum ada di Script Properties.');if(!ids.length)throw new Error('LAVI_FINANCE_TELEGRAM_ALLOWED_CHAT_IDS belum ada.');
    const me=tg_('getMe',{},1),key=getOrCreateWebhookKey_();
    const url='https://lavi-finance-new.latieftjm.workers.dev/telegram-webhook';
    tg_('setMyCommands',{commands:[{command:'start',description:'Buka Menu Utama'},{command:'menu',description:'Menu Interaktif Keuangan'},{command:'total',description:'Cek Saldo Cepat'}]},1);
    const hook=tg_('setWebhook',{url:url,secret_token:relaySecret_(),drop_pending_updates:true,allowed_updates:['message','callback_query']},1);
    return {ok:true,version:VERSION,botConfigured:!!me,username:me&&me.username?('@'+me.username):'',allowedChats:ids.length,webhookConfigured:!!hook,webhookBase:url};
  }
  function status_(){let me=null,wh=null,error='';try{me=tg_('getMe',{},0);wh=tg_('getWebhookInfo',{},0);}catch(e){error=String(e.message||e);}return {ok:!!me&&!!wh,version:VERSION,tokenConfigured:!!token_(),allowedChats:allowedIds_().length,webhookKeyConfigured:!!webhookKey_(),bot:me?{id:me.id,username:me.username||''}:null,webhook:wh?{url:wh.url||'',pendingUpdateCount:wh.pending_update_count||0,lastErrorDate:wh.last_error_date||0,lastErrorMessage:wh.last_error_message||''}:null,error:error};}
  function selfTest_(){
    const sample=[
      {id:'TX-TEST001',tanggal:'12/09/2026',jenis:'Pengeluaran',kategoriPerson:'Abi',kategoriPilihan:'Makanan & Minuman',jenisSaldo:'Cash',sumberDana:'Cash',tujuanDana:'',nominal:25000,keterangan:'Test'},
      {id:'TX-TEST002',tanggal:'12/09/2026',jenis:'Pemasukan',kategoriPerson:'Abi',kategoriPilihan:'Gaji / Upah',jenisSaldo:'Bank Jago',sumberDana:'Bank Jago',tujuanDana:'',nominal:1000000,keterangan:'Test'}
    ];
    const natural=parseNatural_('pengeluaran Abi bulan ini makanan');
    const xlsx=buildXlsx_(sample,'selftest.xlsx');
    const entries=Utilities.unzip(Utilities.newBlob(xlsx.getBytes(),'application/zip','selftest.zip')).map(b=>b.getName()).sort();
    const pdf=buildPdf_(sample,'selftest.pdf','Self Test');
    const pdfHead=Utilities.newBlob(pdf.getBytes().slice(0,8)).getDataAsString();
    return {
      ok: natural.jenis==='Pengeluaran' && natural.person==='Abi' && natural.date==='month' && natural.keyword.indexOf('makanan')>=0 && entries.indexOf('xl/worksheets/sheet1.xml')>=0 && pdfHead.indexOf('%PDF-1.4')===0,
      version:VERSION,
      natural:natural,
      xlsx:{bytes:xlsx.getBytes().length,entries:entries},
      pdf:{bytes:pdf.getBytes().length,header:pdfHead}
    };
  }
  function isWebhook_(e,payload){return !!(payload&&payload.update_id!=null&&e&&e.parameter&&String(e.parameter.action||'')==='telegramWebhook');}

  return Object.freeze({handleUpdate:handleUpdate_,relayGet:relayGet_,relaySecretHash:relaySecretHash_,setup:setup_,status:status_,selfTest:selfTest_,resetSession:function(chatId){props_().deleteProperty(sessionKey_(chatId));return {ok:true};},isWebhook:isWebhook_});
})();

function handleLaviTelegramWebhook_(e, payload) { return LAVI_FINANCE_TELEGRAM.handleUpdate(e,payload); }
function isLaviTelegramWebhookRequest_(e, payload) { return LAVI_FINANCE_TELEGRAM.isWebhook(e,payload); }
function setupLaviFinanceTelegram() { return LAVI_FINANCE_TELEGRAM.setup(); }
function checkLaviFinanceTelegramStatus() { const r=LAVI_FINANCE_TELEGRAM.status(); console.log(JSON.stringify(r,null,2)); return r; }
function resetLaviFinanceTelegramSession(chatId) { return LAVI_FINANCE_TELEGRAM.resetSession(chatId); }

function handleLaviTelegramRelayGet_(e) { return LAVI_FINANCE_TELEGRAM.relayGet(e); }
function getLaviTelegramRelaySecretHashSafe_() { return LAVI_FINANCE_TELEGRAM.relaySecretHash(); }

function testLaviFinanceTelegramFeatures() { const r=LAVI_FINANCE_TELEGRAM.selfTest(); console.log(JSON.stringify(r,null,2)); return r; }
